### ISSUE TITLE
GET /redfish/v1/Systems/{identifier} - returns syntax error

### ISSUE THREAD

**Issue by derrickostertag** [RackHD/RackHD#107]
GET /redfish/v1/Systems/{identifier} - returns a syntax error using a curl command and through the swagger-ui

```
curl -X GET --header 'Accept: application/json' --header 'Authorization: JWT invalid' 'http://172.18.1.50:8080/redfish/v1/Systems/56cc6fc32f60fdb3077b8714'

{"name":"SyntaxError","message":"Unexpected token N","stack":"SyntaxError: Unexpected token N
    at Object.parse (native)
    at /var/renasar/on-http/lib/services/redfish-validator-service.js:104:29
    at b (domain.js:183:18)
    at tryCatcher (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:459:13)","context":{}}

osterd2@lab04:~/Dev/rackfish_tests/rackfish_walk$ 
```

**Comment by heckj** [comment]
. @jlongever FYI

**Comment by jlongever** [comment]
@derrickostertag can you verify the node's catalog data?  dmi and ohai?   Running against quanta and rinjin renders correctly:

```
jlongever@kickseed:~$ curl -X GET --header 'Accept: application/json' --header 'Authorization: JWT invalid' localhost:8080/redfish/v1/Systems/56cdff0617006af427f7cb22 | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1616  100  1616    0     0  32782      0 --:--:-- --:--:-- --:--:-- 32979
{
    "@odata.context": "/redfish/v1/$metadata#Systems/Members/$entity",
    "@odata.id": "/redfish/v1/Systems/56cdff0617006af427f7cb22",
    "@odata.type": "#ComputerSystem.1.0.0.ComputerSystem",
    "Actions": {
        "#ComputerSystem.Reset": {
            "target": "/redfish/v1/Systems/56cdff0617006af427f7cb22/Actions/ComputerSystem.Reset"
        },
        "Oem": {
            "RackHD": {
                "#RackHD.BootImage": {
                    "target": "/redfish/v1/Systems/56cdff0617006af427f7cb22/Actions/RackHD.BootImage"
                }
            }
        }
    },
    "AssetTag": "FC6PL151200002_100-564-404-00",
    "BiosVersion": "SE5C610.86B.01.01.0005.101720141054 0.0 10/17/2014",
    "Boot": {},
    "Description": "",
    "EthernetInterfaces": {
        "@odata.id": "/redfish/v1/Systems/56cdff0617006af427f7cb22/EthernetInterfaces"
    },
    "HostName": "",
    "Id": "56cdff0617006af427f7cb22",
    "IndicatorLED": "Off",
    "Links": {
        "Chassis": [
            {
                "@odata.id": "/redfish/v1/Chassis/56cdff4b50e3b10128f79a03"
            }
        ],
        "Chassis@odata.count": 1,
        "CooledBy": [],
        "CooledBy@odata.count": 0,
        "ManagedBy": [],
        "ManagedBy@odata.count": 0,
        "Oem": {},
        "PoweredBy": [],
        "PoweredBy@odata.count": 0
    },
    "LogServices": {
        "@odata.id": "/redfish/v1/Systems/56cdff0617006af427f7cb22/LogServices"
    },
    "Manufacturer": "",
    "MemorySummary": {
        "Status": {},
        "TotalSystemMemoryGiB": 64
    },
    "Model": "S2600KP",
    "Name": "Computer System",
    "Oem": {},
    "PartNumber": "",
    "PowerState": "On",
    "ProcessorSummary": {
        "Count": 2,
        "Model": "Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz",
        "Status": {}
    },
    "Processors": {
        "@odata.id": "/redfish/v1/Systems/56cdff0617006af427f7cb22/Processors"
    },
    "SKU": "SKU Number",
    "SerialNumber": "FC6PL151200002",
    "SimpleStorage": {
        "@odata.id": "/redfish/v1/Systems/56cdff0617006af427f7cb22/SimpleStorage"
    },
    "Status": {},
    "SystemType": "Physical",
    "UUID": "00b497d8-7c72-e511-a310-001e67c8003f"
}
```

**Comment by jlongever** [comment]
@zyoung51

**Comment by jlongever** [comment]
@derrickostertag the data rendered in the redfish output depends on specific cataloged data;   @benbp noticed some data elements such as BIOS version on a virtualbox VM doesn't exist.  this may cause validation errors.   Could you confirm which compute node type you're on?

**Comment by jlongever** [comment]
@derrickostertag could you dump out dmi.data['Memory Device'].  It's possible some are set to "No module installed".  Something we need to account for.

**Comment by jlongever** [comment]
@derrickostertag right now looks like it's due to some dmi.data['Memory Device'] etries having NaN values.   @benbp will include the fix in his on-http PR updates that resolve some other taskgraph refactoring issues.   

For now if you want,  you can edit file: on-http/data/templates/redfish.1.0.0.computersystem.1.0.0.json and replace the MemorySummary object with the following code:

```
    "MemorySummary": {
        <% var memsize = 0; %>
        <% dmi.data['Memory Device'].forEach(function(dev) { %>
        <%     var size = dev.Size.split(' ')[0]; %>
        <%     size = isNaN(size) ? 0 : size; %>
        <%     memsize = memsize + parseInt(size); %>
        <% }); %>
        <% memsize = memsize / 1024; %>
        "TotalSystemMemoryGiB": <%= memsize %>,
        "Status": {}
    },
```

**Comment by derrickostertag** [comment]
@jlongever Patched worked for Phoenix. I haven't ran it on other nodes that were failing.
Thanks!

**Comment by jlongever** [comment]
@derrickostertag good stuff.   Feel free to pull down master as well since the fix was committed last night.
