### ISSUE TITLE
GET /redfish/v1/Systems/{identifier}/LogService/{log_name}/Entries/{entry_id} - returns a ValidationError

### ISSUE THREAD

**Issue by derrickostertag** [RackHD/RackHD#108]
**GET /redfish/v1/Systems/{identifier}/LogService/{log_name}/Entries/{entry_id}** returns a validation error

```
curl http://172.18.1.50:8080/redfish/v1/Systems/56cc6fef2f60fdb3077b871d/LogServices/SEL/Entries/e22 | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1154  100  1154    0     0  24896      0 --:--:-- --:--:-- --:--:-- 25086
{
    "context": {},
    "message": "ValidationError: No enum match for: \"Asserted\"",
    "name": "Error",
    "stack": "Error: ValidationError: No enum match for: \"Asserted\"
    at /var/renasar/on-http/lib/services/redfish-validator-service.js:115:35
    at b (domain.js:183:18)
    at tryCatcher (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23
    at Promise._settlePromiseFromHandler (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:459:13)"
}
```

**Comment by heckj** [comment]
@derrickostertag just double-checking, is this off the master branch? What machines were set up behind this that you discovered, but hit this issue with?

**Comment by heckj** [comment]
. @jlongever FYI

**Comment by jlongever** [comment]
@zyoung51

**Comment by jlongever** [comment]
@derrickostertag is this a clone of recent master?

**Comment by jlongever** [comment]
Nevermind,  looks like the SEL value isn't matching the expected LogEntryEntryCode enum value.
