### ISSUE TITLE
npm 1.3.10 prunes out redfish-node module

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#117]
We are working on upgrading npm on our build servers to 1.4, but I am opening this issue to track the problem in case someone else tries to use the same build process with 1.3.10 in on-taskgraph and on-http.

The on-taskgraph and on-http build process (both .travis.yml and HWIMO-BUILD) performs an npm install followed by an npm prune --production to prune out the development modules.  However, we have found with npm 1.3.10, it also prunes out the redfish-node module from the on-tasks/node-modules which is required for on-taskgraph and on-http.

After the npm install:
```
lab05:~/work/on-taskgraph/packagebuild$ ls node_modules/on-tasks/node_modules/
redfish-node  xml2js
```

Followed by the prune:

```
lab05:~/work/on-taskgraph/packagebuild$ npm prune --production
unbuild redfish-node@0.0.1
unbuild chai-as-promised@4.3.0
unbuild grunt-mocha-istanbul@2.4.0
unbuild sinon-chai@2.8.0
unbuild xunit-file@0.0.6
unbuild sinon-as-promised@2.0.3
unbuild chai@2.3.0
unbuild grunt-mocha-test@0.12.7
unbuild sinon@1.17.3
unbuild grunt-notify@0.4.5
unbuild jsdoc@3.4.0
unbuild mocha@2.4.5
unbuild grunt@0.4.5
unbuild grunt-cli@0.1.13
unbuild grunt-contrib-watch@0.6.1
unbuild jshint@2.9.1
unbuild supertest@0.15.0
unbuild coveralls@2.11.8
unbuild grunt-contrib-jshint@0.11.3
unbuild istanbul@0.3.22
lab05:~/work/on-taskgraph/packagebuild$ ls node_modules/on-tasks/node_modules/
xml2js
```

**Comment by johren** [comment]
This results (in our case) in on-taskgraph and on-http debian packages with no redfish-node module.  This causes both of these services to crash.  The following is found in both /var/log/upstart/on-taskgraph.log and /var/log/upstart/on-http.log:

```
module.js:340
    throw err;
    ^
Error: Cannot find module 'redfish-node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/renasar/on-taskgraph/node_modules/on-tasks/lib/jobs/redfish-discovery.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /var/renasar/on-taskgraph/node_modules/on-core/lib/di.js:529:24
    at arrayMap (/var/renasar/on-taskgraph/node_modules/lodash/index.js:1406:25)
    at Function.map (/var/renasar/on-taskgraph/node_modules/lodash/index.js:6710:14)
    at Object.requireGlob (/var/renasar/on-taskgraph/node_modules/on-core/lib/di.js:528:14)
    at Object.<anonymous> (/var/renasar/on-taskgraph/node_modules/on-tasks/index.js:12:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by heckj** [comment]
Partial fix with https://github.com/RackHD/on-taskgraph/pull/72

**Comment by heckj** [comment]
also resolved with https://github.com/RackHD/on-http/pull/167
