### ISSUE TITLE
GET /api/1.1/lookups - JSON Schema Violation

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#122]
On some installations, I am getting "JSON Schema Violation" when trying to access the GET method on the /api/1.1/lookups API.
```
$ curl localhost:8080/api/common/lookups
{"message":"SchemaError: JSON Schema Violation"}
```

From the on-http.log file:
```
[debug] [2016-03-04T20:46:30.500Z] [on-http] [Http.Server] [Server] http: GET 500 18.243 - /api/common/lookups
 -> /lib/services/http-service.js:298
ipAddress: 127.0.0.1
Error: SchemaError: JSON Schema Violation
    at Lookup.ValidatableFactory.Validatable.validate (/var/renasar/on-http/node_modules/on-core/lib/common/validatable.js:46:35)
    at Lookup.ValidatableFactory.Validatable.validateAsModel (/var/renasar/on-http/node_modules/on-core/lib/common/validatable.js:59:21)
    at /var/renasar/on-http/lib/services/rest-api-service.js:400:35
    at tryCatcher (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:459:13)
```

Full set of logs can be found here:  https://web.hwimo.lab.emc.com/qa/log/QA_test_results/BR_HWIMO/ONRACK_onrack-devel/ora_smoke_test_master.py.ON.stack11-ora.admin/TM_20160304_20_02_14/

**Comment by heckj** [comment]
@benbp @jlongever @brianparry seeing a `SchemaError` on a GET is surprising. Did we make a change recently to the models or data in a model that we'd add asynchronously from the lookups API that isn't reflected in the schema for that model?

**Comment by heckj** [comment]
@benbp any brilliant suggestions for a tool to convert a ".bson" file into a JSON data structure? The dumps that @johren provided has the raw BSON, but a touch hard to see translate that manually :-)

**Comment by benbp** [comment]
You need to use mongoload or mongoimport, I forget which.

**Comment by heckj** [comment]
`mongorestore pxe`, after which I could do:

```
mongo
use pie
db.lookups.find()
```

which resulted in the following output:
```
{ "_id" : ObjectId("56d9ebb54cf539ff365d4a72"), "ipAddress" : "172.31.128.2", "macAddress" : "00:1e:67:d5:df:e7", "updatedAt" : ISODate("2016-03-04T20:10:29.264Z") }
{ "_id" : ObjectId("56d9ebb54cf539ff365d4a73"), "ipAddress" : "172.31.128.4", "macAddress" : "00:1e:67:d5:e1:9a", "updatedAt" : ISODate("2016-03-04T20:10:29.268Z") }
{ "_id" : ObjectId("56d9ebb54cf539ff365d4a74"), "ipAddress" : "172.31.128.3", "macAddress" : "00:1e:67:d5:d7:4f", "updatedAt" : ISODate("2016-03-04T20:10:29.271Z") }
{ "_id" : ObjectId("56d9ebb54cf539ff365d4a75"), "ipAddress" : "172.31.128.5", "macAddress" : "00:1e:67:c8:00:42", "updatedAt" : ISODate("2016-03-04T20:10:29.274Z") }
{ "_id" : ObjectId("56d9ebc44cf539ff365d4a76"), "ipAddress" : "172.31.128.6", "macAddress" : "2c:60:0c:6f:17:3b", "updatedAt" : ISODate("2016-03-04T20:10:44.243Z") }
{ "_id" : ObjectId("56d9ebc44cf539ff365d4a77"), "ipAddress" : "172.31.128.7", "macAddress" : "2c:60:0c:6f:17:4d", "updatedAt" : ISODate("2016-03-04T20:10:44.246Z") }
{ "_id" : ObjectId("56d9ebc44cf539ff365d4a78"), "ipAddress" : "172.31.128.8", "macAddress" : "2c:60:0c:6f:16:6d", "updatedAt" : ISODate("2016-03-04T20:10:44.248Z") }
{ "_id" : ObjectId("56d9ebd34cf539ff365d4a79"), "ipAddress" : "172.31.128.9", "macAddress" : "2c:60:0c:83:74:9c", "updatedAt" : ISODate("2016-03-04T20:10:59.211Z") }
{ "_id" : ObjectId("56d9ec324cf539ff365d4a7b"), "ipAddress" : "172.31.128.12", "macAddress" : "00:1e:67:d5:d7:4b", "node" : ObjectId("56d9ec59bd3413ad07e6ab64"), "updatedAt" : ISODate("2016-03-04T20:17:54.265Z") }
{ "_id" : ObjectId("56d9ec374cf539ff365d4a7c"), "ipAddress" : "172.31.128.11", "macAddress" : "00:1e:67:d5:e1:96", "node" : ObjectId("56d9ec5bbd3413ad07e6ab6e"), "updatedAt" : ISODate("2016-03-04T20:14:35.851Z") }
{ "_id" : ObjectId("56d9ec374cf539ff365d4a7d"), "ipAddress" : null, "macAddress" : "00:1e:67:d5:df:e3", "node" : ObjectId("56d9ec5ebd3413ad07e6ab78"), "updatedAt" : ISODate("2016-03-04T20:17:54.262Z") }
{ "_id" : ObjectId("56d9ec414cf539ff365d4a7e"), "ipAddress" : "172.31.128.10", "macAddress" : "00:1e:67:c8:00:3e", "node" : ObjectId("56d9ec69bd3413ad07e6ab82"), "updatedAt" : ISODate("2016-03-04T20:18:14.288Z") }
{ "node" : ObjectId("56d9ec59bd3413ad07e6ab64"), "macAddress" : "00:1e:67:c5:be:ea", "createdAt" : ISODate("2016-03-04T20:13:13.379Z"), "updatedAt" : ISODate("2016-03-04T20:14:32.880Z"), "_id" : ObjectId("56d9ec59bd3413ad07e6ab65") }
{ "node" : ObjectId("56d9ec59bd3413ad07e6ab64"), "macAddress" : "00:1e:67:c5:be:eb", "createdAt" : ISODate("2016-03-04T20:13:13.384Z"), "updatedAt" : ISODate("2016-03-04T20:14:32.884Z"), "_id" : ObjectId("56d9ec59bd3413ad07e6ab66") }
{ "node" : ObjectId("56d9ec59bd3413ad07e6ab64"), "macAddress" : "00:1e:67:d5:d7:4c", "createdAt" : ISODate("2016-03-04T20:13:13.401Z"), "updatedAt" : ISODate("2016-03-04T20:14:32.889Z"), "_id" : ObjectId("56d9ec59bd3413ad07e6ab67") }
{ "node" : ObjectId("56d9ec5bbd3413ad07e6ab6e"), "macAddress" : "00:1e:67:c5:be:d6", "createdAt" : ISODate("2016-03-04T20:13:15.763Z"), "updatedAt" : ISODate("2016-03-04T20:14:35.848Z"), "_id" : ObjectId("56d9ec5bbd3413ad07e6ab6f") }
{ "node" : ObjectId("56d9ec5bbd3413ad07e6ab6e"), "macAddress" : "00:1e:67:c5:be:d7", "createdAt" : ISODate("2016-03-04T20:13:15.766Z"), "updatedAt" : ISODate("2016-03-04T20:14:35.850Z"), "_id" : ObjectId("56d9ec5bbd3413ad07e6ab70") }
{ "node" : ObjectId("56d9ec5bbd3413ad07e6ab6e"), "macAddress" : "00:1e:67:d5:e1:97", "createdAt" : ISODate("2016-03-04T20:13:15.774Z"), "updatedAt" : ISODate("2016-03-04T20:14:35.853Z"), "_id" : ObjectId("56d9ec5bbd3413ad07e6ab71") }
{ "node" : ObjectId("56d9ec5ebd3413ad07e6ab78"), "macAddress" : "00:1e:67:d0:45:28", "createdAt" : ISODate("2016-03-04T20:13:18.996Z"), "updatedAt" : ISODate("2016-03-04T20:14:38.829Z"), "_id" : ObjectId("56d9ec5ebd3413ad07e6ab79") }
{ "node" : ObjectId("56d9ec5ebd3413ad07e6ab78"), "macAddress" : "00:1e:67:d0:45:29", "createdAt" : ISODate("2016-03-04T20:13:19.002Z"), "updatedAt" : ISODate("2016-03-04T20:14:38.831Z"), "_id" : ObjectId("56d9ec5fbd3413ad07e6ab7a") }
{ "node" : ObjectId("56d9ec5ebd3413ad07e6ab78"), "macAddress" : "00:1e:67:d5:df:e4", "createdAt" : ISODate("2016-03-04T20:13:19.011Z"), "updatedAt" : ISODate("2016-03-04T20:14:38.834Z"), "_id" : ObjectId("56d9ec5fbd3413ad07e6ab7b") }
{ "node" : ObjectId("56d9ec69bd3413ad07e6ab82"), "macAddress" : "00:1e:67:c5:b8:fa", "createdAt" : ISODate("2016-03-04T20:13:29.995Z"), "updatedAt" : ISODate("2016-03-04T20:14:53.685Z"), "_id" : ObjectId("56d9ec69bd3413ad07e6ab83") }
{ "node" : ObjectId("56d9ec69bd3413ad07e6ab82"), "macAddress" : "00:1e:67:c5:b8:fb", "createdAt" : ISODate("2016-03-04T20:13:29.999Z"), "updatedAt" : ISODate("2016-03-04T20:14:53.689Z"), "_id" : ObjectId("56d9ec69bd3413ad07e6ab84") }
{ "node" : ObjectId("56d9ec69bd3413ad07e6ab82"), "macAddress" : "00:1e:67:c8:00:3f", "createdAt" : ISODate("2016-03-04T20:13:30.006Z"), "updatedAt" : ISODate("2016-03-04T20:14:53.692Z"), "_id" : ObjectId("56d9ec6abd3413ad07e6ab85") }
{ "_id" : ObjectId("56d9ec874cf539ff365d4a87"), "ipAddress" : "172.31.128.14", "macAddress" : "2c:60:0c:6f:b7:95", "node" : ObjectId("56d9ec94bd3413ad07e6ab94"), "updatedAt" : ISODate("2016-03-04T20:15:25.041Z") }
{ "_id" : ObjectId("56d9ec8c4cf539ff365d4a8a"), "ipAddress" : "172.31.128.15", "macAddress" : "2c:60:0c:6f:b7:db", "node" : ObjectId("56d9ec96bd3413ad07e6ab9c"), "updatedAt" : ISODate("2016-03-04T20:15:27.077Z") }
{ "_id" : ObjectId("56d9ec8c4cf539ff365d4a8b"), "ipAddress" : "172.31.128.16", "macAddress" : "2c:60:0c:6f:b6:ed", "node" : ObjectId("56d9ec93bd3413ad07e6ab8c"), "updatedAt" : ISODate("2016-03-04T20:15:23.534Z") }
{ "node" : ObjectId("56d9ec93bd3413ad07e6ab8c"), "macAddress" : "2c:60:0c:6f:b6:ee", "createdAt" : ISODate("2016-03-04T20:14:11.662Z"), "updatedAt" : ISODate("2016-03-04T20:15:23.536Z"), "_id" : ObjectId("56d9ec93bd3413ad07e6ab8d") }
{ "node" : ObjectId("56d9ec94bd3413ad07e6ab94"), "macAddress" : "2c:60:0c:6f:b7:96", "createdAt" : ISODate("2016-03-04T20:14:12.111Z"), "updatedAt" : ISODate("2016-03-04T20:15:25.043Z"), "_id" : ObjectId("56d9ec94bd3413ad07e6ab95") }
{ "node" : ObjectId("56d9ec96bd3413ad07e6ab9c"), "macAddress" : "2c:60:0c:6f:b7:dc", "createdAt" : ISODate("2016-03-04T20:14:14.021Z"), "updatedAt" : ISODate("2016-03-04T20:15:27.079Z"), "_id" : ObjectId("56d9ec96bd3413ad07e6ab9d") }
{ "_id" : ObjectId("56d9eca04cf539ff365d4a94"), "ipAddress" : "172.31.128.17", "macAddress" : "2c:60:0c:83:72:19", "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "updatedAt" : ISODate("2016-03-04T20:16:52.043Z") }
{ "_id" : ObjectId("56d9ecaa4cf539ff365d4a95"), "ipAddress" : "172.31.128.21", "macAddress" : "2c:60:0c:7b:fd:3c", "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "updatedAt" : ISODate("2016-03-04T20:26:24.301Z") }
{ "_id" : ObjectId("56d9ecdc4cf539ff365d4a9d"), "ipAddress" : "172.31.128.19", "macAddress" : "2c:60:0c:83:72:1a", "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "updatedAt" : ISODate("2016-03-04T20:16:52.046Z") }
{ "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "macAddress" : "2c:60:0c:7b:fd:3d", "createdAt" : ISODate("2016-03-04T20:15:37.196Z"), "updatedAt" : ISODate("2016-03-04T20:16:52.050Z"), "_id" : ObjectId("56d9ece9bd3413ad07e6aba5") }
{ "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "macAddress" : "90:e2:ba:7e:c0:10", "createdAt" : ISODate("2016-03-04T20:15:37.200Z"), "updatedAt" : ISODate("2016-03-04T20:15:37.200Z"), "_id" : ObjectId("56d9ece9bd3413ad07e6aba6") }
{ "node" : ObjectId("56d9ece9bd3413ad07e6aba4"), "macAddress" : "90:e2:ba:7e:c0:11", "createdAt" : ISODate("2016-03-04T20:15:37.203Z"), "updatedAt" : ISODate("2016-03-04T20:15:37.203Z"), "_id" : ObjectId("56d9ece9bd3413ad07e6aba7") }
```

**Comment by benbp** [comment]
@heckj I think I found the issue here. We are setting the ipAddress field to `null` on lookup conflicts, whereas before we were just deleting it. This causes a schema violation since `null` does not match the IP address regex. @tldavies we should switch the null update to use `$unset` instead: https://docs.mongodb.org/manual/reference/operator/update/unset/

**Comment by johren** [comment]
We have hit this in 22 of the last 34 test runs.  This is a blocking issue for us.

**Comment by tldavies** [comment]
@johren There is a fix for this is in https://github.com/RackHD/on-core/pull/98

So when that gets merged it should be fixed.
