### ISSUE TITLE
http service hang after intentionally post a wrong lookup entry with duplicated macAddress

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#129]
This issue can be always reproduced using lastest code (same behavior before&after merging this PR: https://github.com/RackHD/on-core/pull/98), below is the reproduce steps:

#### 1. List all lookups:
```
curl http://localhost:8080/api/1.1/lookups | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   737  100   737    0     0  57912      0 --:--:-- --:--:-- --:--:-- 61416
[
    {
        "createdAt": "2016-01-07T09:24:25.313Z",
        "id": "568e2ec9f1ec7353052ae10f",
        "ipAddress": "172.31.128.38",
        "macAddress": "52:54:be:ef:a2:a3",
        "node": "",
        "updatedAt": "2016-01-08T03:03:59.956Z"
    },
    {
        "createdAt": "2016-01-07T09:25:30.228Z",
        "id": "568e2f0af1ec7353052ae112",
        "ipAddress": "172.31.128.37",
        "macAddress": "00:50:56:aa:a2:a3",
        "updatedAt": "2016-01-07T09:25:30.228Z"
    },
    {
        "createdAt": "2016-01-08T02:32:55.307Z",
        "id": "568f1fd7a33dcea40767a442",
        "ipAddress": "172.31.128.39",
        "macAddress": "00:50:56:aa:12:26",
        "updatedAt": "2016-01-08T02:32:55.307Z"
    },
    {
        "createdAt": "2016-01-08T02:33:20.320Z",
        "id": "568f1ff0a33dcea40767a443",
        "ipAddress": "172.31.128.40",
        "macAddress": "52:54:be:ef:12:26",
        "node": "568f1ff9d786788607c7dbab",
        "updatedAt": "2016-01-08T02:34:16.938Z"
    }
]
```

#### 2. POST a new lookup entry
**NOTE**: The new lookup entry has the same `macAddress` (*52:54:be:ef:12:26*) with last lookup entry in the step1's list, this request doesn't have any response even after 1 min and 50 seconds!
```
curl -X POST -H "Content-Type:application/json" http://localhost:8080/api/1.1/lookups -d '{"ipAddress": "10.171.75.107","macAddress": "52:54:be:ef:12:26","node": "568f1ff9d786788607c7dbab"}' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    99    0     0    0    99      0      0 --:--:--  0:01:50 --:--:--     0
```

#### 4. Send another get request will always hang:
**NOTE**: Those python output is due to I typed the *CTRL+C* to forcely stop curl command.
```
onrack@~/src/on-core> curl http://localhost:8080/api/1.1/lookups | python -m json.tool                                                                                                                % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/json/tool.py", line 40, in <module>
    main()
  File "/usr/lib/python2.7/json/tool.py", line 30, in main
    obj = json.load(infile)
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
KeyboardInterrupt

onrack@~/src/on-core> curl http://localhost:8080/api/1.1/nodes | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/json/tool.py", line 40, in <module>
    main()
  File "/usr/lib/python2.7/json/tool.py", line 30, in main
    obj = json.load(infile)
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
KeyboardInterrupt
```

### Expected Behavior
RackHD rejects the wrong lookup entry and HTTP service is not impacted.

**Comment by benbp** [comment]
The error isn't getting caught, but I was able to get it in the debugger:

```
exception in /Users/brodeb/repos/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:122
TypeError: Cannot assign to read only property 'toJSON' of MongoError: E11000 duplicate key error index: pxe.lookups.$macAddress_1_ipAdd
```

So we're correctly enforcing unique indexes, but I think because we're doing it at the mongo level now, something in the waterline library is not handling this error properly.

**Comment by benbp** [comment]
I think we're potentially hitting this because waterline may be overriding this error prototype???

https://github.com/balderdashy/waterline/blob/master/lib/waterline/error/WLError.js#L52

**Comment by benbp** [comment]
Not waterline, it's us: https://github.com/RackHD/on-core/blob/f5ad4f4888f6a892b6db97d83d0086d5c102f613/lib/extensions.js#L11-L29

**Comment by benbp** [comment]
Fixes up at https://github.com/RackHD/on-core/pull/99
