### ISSUE TITLE
run sku specified graph fails with "AssertionError: undefined (uuid) is required"

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#138]
This issue is caught from discussion with @ytjohn in the slack channel.

The SKU discovery graph always fails with following errors:
```
name:           SKU Discovery
_id: 
  _bsontype: ObjectID
  id:        Vé5ëpý¥��Ö§�
tasks: 
  319ea63c-5d93-420e-b421-bc0005989481: 
    error: 
      """
        AssertionError: undefined (uuid) is required
            at AssertService.(anonymous function) [as uuid] (/var/renasar/on-taskgraph/node_modules/on-core/lib/common/assert.js:30:28)
            at TaskGraphRunnerProtocol.runTaskGraph (/var/renasar/on-taskgraph/node_modules/on-core/lib/protocol/task-graph-runner.js:232:16)
            at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/jobs/run-sku-graph.js:87:42
            at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
            at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
            at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
            at Promise._settlePromises (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
            at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
            at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
            at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
            at process._tickDomainCallback (node.js:459:13)
      """
    friendlyName:     Run SKU-specific graph
```

The SKU info is defined as following:
```json
{
    "name": "Noop OBM settings for VirtualBox nodes",
    "injectableName": "SKU.InstallTrusty",
    "discoveryGraphName": "Graph.DefaultVirtualBox.InstallTrusty",
    "discoveryGraphOptions": {},
    "rules": [
        {
            "path": "dmi.System Information.Product Name",
            "equals": "VirtualBox"
        }
    ]
}
```

Some detail error log: https://gist.github.com/ytjohn/e181b52f4d1dd308bb9b

**Comment by yyscamper** [comment]
The error happened on this line: https://github.com/RackHD/on-tasks/blob/master/lib/jobs/run-sku-graph.js#L87, after the workflow H/A design, the first argument in the function `runTaskGraph` should be the graph instanceId, not the graph injectable name. on-http had the same issue before, the fix is to change the `runTaskGraph` to `createAndRunGraph` (see this implementation: https://github.com/RackHD/on-http/blob/master/lib/services/workflow-api-service.js#L39)
