### ISSUE TITLE
Lookups collection vulnerable to null ipAddress duplicate key errors.

### ISSUE THREAD

**Issue by rolandpoulter** [RackHD/RackHD#139]
Encountered a duplicate key error running RackHD in Docker while testing with real hardware. It is possible that this issue is only related to running RackHD with Docker. However I don't believe this to be the case.

Here is a snippet of the error.
```
2016-03-15T13:52:53.781601332Z [error] [2016-03-15T13:52:53.776Z] [on-http] [common-api-presenter] [Server] [Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undefined:
2016-03-15T13:52:53.781644070Z  • ipAddress
2016-03-15T13:52:53.781656062Z    • A record with that `ipAddress` already exists (`null`).
```

I'm told it is a likely scenario for lookup records to have a `macAddress` defined with a `null` `ipAddress`. We recently changed our indexes on the lookups collection. See https://github.com/RackHD/on-core/pull/99/files#diff-3d6fb4b9c8b9cd924c12b1e4e2066f35R115

I think we need to change the `ipAddress` index to a compound index on both `macAddress` and `ipAddress`.

**Comment by rolandpoulter** [comment]
More detailed logs:
```
onrack@linux-jx80:/RackHD/docker> 2016-03-15T13:50:00.035784152Z [debug] [2016-03-15T13:50:00.030Z] [on-syslog] [Services.ErrorPublisher] [Server] Event Loop Blocked
2016-03-15T13:50:00.035842312Z  -> /RackHD/on-core/lib/services/error-publisher.js:85
2016-03-15T13:50:00.037378006Z host:     linux-jx80
2016-03-15T13:50:00.037401121Z name:     on-syslog
2016-03-15T13:50:00.037409700Z severity: debug
2016-03-15T13:50:00.037417315Z ms:       23
2016-03-15T13:50:42.440716416Z Tue Mar 15 13:50:42 UTC 2016
2016-03-15T13:51:00.127932984Z [debug] [2016-03-15T13:51:00.116Z] [on-syslog] [Services.ErrorPublisher] [Server] Event Loop Blocked
2016-03-15T13:51:00.128861697Z  -> /RackHD/on-core/lib/services/error-publisher.js:85
2016-03-15T13:51:00.129160251Z host:     linux-jx80
2016-03-15T13:51:00.129188566Z name:     on-syslog
2016-03-15T13:51:00.129197601Z severity: debug
2016-03-15T13:51:00.129217501Z ms:       11
2016-03-15T13:51:03.949535445Z [debug] [2016-03-15T13:51:03.943Z] [on-tftp] [Services.ErrorPublisher] [Server] Event Loop Blocked
2016-03-15T13:51:03.949575505Z  -> /RackHD/on-core/lib/services/error-publisher.js:85
2016-03-15T13:51:03.949595803Z host:     linux-jx80
2016-03-15T13:51:03.949604483Z name:     on-tftp
2016-03-15T13:51:03.949611907Z severity: debug
2016-03-15T13:51:03.949619117Z ms:       12
2016-03-15T13:51:12.230753858Z [debug] [2016-03-15T13:51:12.228Z] [on-taskgraph] [Services.ErrorPublisher] [Server] Event Loop Blocked
2016-03-15T13:51:12.230938154Z  -> /RackHD/on-core/lib/services/error-publisher.js:85
2016-03-15T13:51:12.231691831Z host:     linux-jx80
2016-03-15T13:51:12.231721909Z name:     on-taskgraph
2016-03-15T13:51:12.231731692Z severity: debug
2016-03-15T13:51:12.231739420Z ms:       12
2016-03-15T13:52:33.036082821Z [debug] [2016-03-15T13:52:33.024Z] [on-dhcp-proxy] [Services.ErrorPublisher] [Server] Event Loop Blocked
2016-03-15T13:52:33.036150260Z  -> /RackHD/on-core/lib/services/error-publisher.js:85
2016-03-15T13:52:33.036788230Z host:     linux-jx80
2016-03-15T13:52:33.036810108Z name:     on-dhcp-proxy
2016-03-15T13:52:33.036818594Z severity: debug
2016-03-15T13:52:33.036825489Z ms:       46
2016-03-15T13:52:33.057833658Z [debug] [2016-03-15T13:52:33.048Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Unknown node 2c:60:0c:83:f4:47. Sending down default bootfile.
2016-03-15T13:52:33.057859941Z  -> /lib/message-handler.js:317
2016-03-15T13:52:33.060505926Z [debug] [2016-03-15T13:52:33.057Z] [on-dhcp-proxy] [Server] [Server] current OutPort => 68
2016-03-15T13:52:33.060530683Z  -> /lib/server.js:39
2016-03-15T13:52:33.062893866Z [debug] [2016-03-15T13:52:32.979Z] [on-dhcp-proxy] [DHCP.parser] [Server] Unhandled DHCP options (97:17,94:3)
2016-03-15T13:52:33.062917975Z  -> /lib/parser.js:331
2016-03-15T13:52:33.062928182Z macaddress: 2c:60:0c:83:f4:47
2016-03-15T13:52:33.081536119Z [warning] [2016-03-15T13:52:33.079Z] [on-tftp] [Tftp.Server] [Server] Tftp error
2016-03-15T13:52:33.081572951Z  -> /lib/server.js:53
2016-03-15T13:52:33.081586528Z file:          monorail.ipxe
2016-03-15T13:52:33.081594520Z remoteAddress: 172.31.128.2
2016-03-15T13:52:33.081601896Z remotePort:    2070
2016-03-15T13:52:33.266534065Z [error] [2016-03-15T13:52:33.264Z] [on-tftp] [Tftp.Server] [Server] Error publishing TFTP success message:
2016-03-15T13:52:33.266578151Z  -> /lib/server.js:85
2016-03-15T13:52:33.267097277Z error:
2016-03-15T13:52:33.267139023Z   message: Lookup Record Not Found (handleCachePromise)
2016-03-15T13:52:33.267149322Z   name:    NotFoundError
2016-03-15T13:52:33.267156981Z   context:
2016-03-15T13:52:33.267172912Z
2016-03-15T13:52:33.267180229Z   status:  404
2016-03-15T13:52:33.272085799Z [debug] [2016-03-15T13:52:33.223Z] [on-tftp] [Tftp.Server] [Server] tftp: 136.377 monorail.ipxe
2016-03-15T13:52:33.272111687Z  -> /lib/server.js:69
2016-03-15T13:52:33.707314740Z [2016-03-15 13:52:33,707][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
2016-03-15T13:52:33.726478524Z [2016-03-15 13:52:33,726][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
2016-03-15T13:52:33.744087831Z [2016-03-15 13:52:33,743][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
2016-03-15T13:52:42.442478758Z Tue Mar 15 13:52:42 UTC 2016
2016-03-15T13:52:44.195457530Z [debug] [2016-03-15T13:52:44.183Z] [on-dhcp-proxy] [DHCP.parser] [Server] Unhandled DHCP options (94:3,175:54,97:17)
2016-03-15T13:52:44.195499354Z  -> /lib/parser.js:331
2016-03-15T13:52:44.195509735Z macaddress: 2c:60:0c:83:f4:47
2016-03-15T13:52:44.205855128Z [debug] [2016-03-15T13:52:44.202Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Unknown node 2c:60:0c:83:f4:47. Sending down default bootfile.
2016-03-15T13:52:44.205879952Z  -> /lib/message-handler.js:317
2016-03-15T13:52:44.211642268Z [debug] [2016-03-15T13:52:44.210Z] [on-dhcp-proxy] [Server] [Server] current OutPort => 68
2016-03-15T13:52:44.211666312Z  -> /lib/server.js:39
2016-03-15T13:52:50.077508120Z [debug] [2016-03-15T13:52:50.073Z] [on-http] [Http.Server] [Server] http: GET 200 56.531 - /api/common/profiles
2016-03-15T13:52:50.077559099Z  -> /lib/services/http-service.js:298
2016-03-15T13:52:50.077573045Z ipAddress: 172.31.128.2
2016-03-15T13:52:50.764547147Z [2016-03-15 13:52:50,764][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
2016-03-15T13:52:53.627205313Z [debug] [2016-03-15T13:52:53.619Z] [on-dhcp-proxy] [DHCP.parser] [Server] Unhandled DHCP options (94:3,175:54,97:17)
2016-03-15T13:52:53.627282826Z  -> /lib/parser.js:331
2016-03-15T13:52:53.627302784Z macaddress: 2c:60:0c:83:f4:47
2016-03-15T13:52:53.635463931Z [debug] [2016-03-15T13:52:53.632Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Unknown node 2c:60:0c:83:f4:47. Sending down default bootfile.
2016-03-15T13:52:53.635498513Z  -> /lib/message-handler.js:317
2016-03-15T13:52:53.638307316Z [debug] [2016-03-15T13:52:53.637Z] [on-dhcp-proxy] [Server] [Server] current OutPort => 68
2016-03-15T13:52:53.638332067Z  -> /lib/server.js:39
2016-03-15T13:52:53.694025043Z [info] [2016-03-15T13:52:53.666Z] [on-syslog] [Syslog] [Server] ipxe: net0: 172.31.128.2/255.255.252.0
2016-03-15T13:52:53.694065799Z  -> /lib/app.js:65
2016-03-15T13:52:53.694618380Z facility: 0
2016-03-15T13:52:53.694640513Z priority: 6
2016-03-15T13:52:53.695463840Z [info] [2016-03-15T13:52:53.668Z] [on-syslog] [Syslog] [Server] ipxe: MonoRail Boilerplate iPXE Completed.
2016-03-15T13:52:53.695486850Z  -> /lib/app.js:65
2016-03-15T13:52:53.695699845Z facility: 0
2016-03-15T13:52:53.695719511Z priority: 6
2016-03-15T13:52:53.697052565Z [info] [2016-03-15T13:52:53.668Z] [on-syslog] [Syslog] [Server] ipxe:
2016-03-15T13:52:53.697080038Z  -> /lib/app.js:65
2016-03-15T13:52:53.697225595Z facility: 0
2016-03-15T13:52:53.697247014Z priority: 6
2016-03-15T13:52:53.698175728Z [info] [2016-03-15T13:52:53.669Z] [on-syslog] [Syslog] [Server] ipxe: http://172.31.128.1:9080/api/common/profiles?macs=2c%3A60%3A0c%3A83%3Af4%3A47&macs=2c%3A60%3A0c%3A83%3Af4%3A48&macs=90%3Ae2%3Ab
2016-03-15T13:52:53.698201217Z  -> /lib/app.js:65
2016-03-15T13:52:53.698578048Z facility: 0
2016-03-15T13:52:53.698597502Z priority: 6
2016-03-15T13:52:53.716035798Z [info] [2016-03-15T13:52:53.642Z] [on-syslog] [Syslog] [Server] ipxe: Configuring (net0 2c:60:0c:83:f4:47).... ok
2016-03-15T13:52:53.716067695Z  -> /lib/app.js:65
2016-03-15T13:52:53.716077883Z facility: 0
2016-03-15T13:52:53.716085429Z priority: 6
2016-03-15T13:52:53.781601332Z [error] [2016-03-15T13:52:53.776Z] [on-http] [common-api-presenter] [Server] [Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undefined:
2016-03-15T13:52:53.781644070Z  • ipAddress
2016-03-15T13:52:53.781656062Z    • A record with that `ipAddress` already exists (`null`).
2016-03-15T13:52:53.781664645Z
2016-03-15T13:52:53.781673358Z  -> /lib/services/common-api-presenter.js:176
2016-03-15T13:52:53.783747701Z [info] [2016-03-15T13:52:53.780Z] [on-syslog] [Syslog] [Server] ipxe: a%3A84%3A2a%3Ac8&macs=90%3Ae2%3Aba%3A84%3A2a%3Ac9... Input/output error (http://ipxe.org/1d0c6439)
2016-03-15T13:52:53.783775516Z  -> /lib/app.js:65
2016-03-15T13:52:53.783784980Z facility: 0
2016-03-15T13:52:53.783792303Z priority: 6
2016-03-15T13:52:53.784681413Z error:
2016-03-15T13:52:53.784707706Z   code:              E_VALIDATION
2016-03-15T13:52:53.784944256Z   invalidAttributes:
2016-03-15T13:52:53.784967004Z     ipAddress:
2016-03-15T13:52:53.784975723Z       -
2016-03-15T13:52:53.784982758Z         rule:    unique
2016-03-15T13:52:53.784989675Z         value:   null
2016-03-15T13:52:53.784996453Z         message: A record with that `ipAddress` already exists (`null`).
2016-03-15T13:52:53.785003329Z   originalError:
2016-03-15T13:52:53.785010197Z     name:         MongoError
2016-03-15T13:52:53.785017405Z     message:      E11000 duplicate key error collection: rackhd.lookups index: ipAddress_1 dup key: { : null }
2016-03-15T13:52:53.785031174Z     driver:       true
2016-03-15T13:52:53.785039199Z     code:         11000
2016-03-15T13:52:53.785050889Z     index:        0
2016-03-15T13:52:53.785068285Z     errmsg:       E11000 duplicate key error collection: rackhd.lookups index: ipAddress_1 dup key: { : null }
2016-03-15T13:52:53.785080489Z     getOperation:
2016-03-15T13:52:53.785087570Z
2016-03-15T13:52:53.785094565Z     toJSON:
2016-03-15T13:52:53.785101330Z
2016-03-15T13:52:53.785108077Z     toString:
2016-03-15T13:52:53.785114826Z
2016-03-15T13:52:53.785121391Z   _e:
2016-03-15T13:52:53.785128100Z     name:         MongoError
2016-03-15T13:52:53.785135088Z     message:      E11000 duplicate key error collection: rackhd.lookups index: ipAddress_1 dup key: { : null }
2016-03-15T13:52:53.785142345Z     driver:       true
2016-03-15T13:52:53.785149169Z     code:         11000
2016-03-15T13:52:53.785155816Z     index:        0
2016-03-15T13:52:53.785162583Z     errmsg:       E11000 duplicate key error collection: rackhd.lookups index: ipAddress_1 dup key: { : null }
2016-03-15T13:52:53.785169644Z     getOperation:
2016-03-15T13:52:53.785176325Z
2016-03-15T13:52:53.785182801Z     toJSON:
2016-03-15T13:52:53.785189506Z
2016-03-15T13:52:53.785196249Z     toString:
2016-03-15T13:52:53.785202982Z
2016-03-15T13:52:53.785209536Z   rawStack:
2016-03-15T13:52:53.785216175Z     """
2016-03-15T13:52:53.785223096Z       MongoError: E11000 duplicate key error collection: rackhd.lookups index: ipAddress_1 dup key: { : null }
2016-03-15T13:52:53.785230911Z           at Function.MongoError.create (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
2016-03-15T13:52:53.785238292Z           at toError (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:114:22)
2016-03-15T13:52:53.785245356Z           at /RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:597:23
2016-03-15T13:52:53.785252399Z           at handleCallback (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:96:12)
2016-03-15T13:52:53.785262144Z           at resultHandler (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/bulk/ordered.js:419:14)
2016-03-15T13:52:53.785269509Z           at /RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:780:13
2016-03-15T13:52:53.785276663Z           at Callbacks.emit (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
2016-03-15T13:52:53.785284117Z           at null.messageHandler (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
2016-03-15T13:52:53.785296800Z           at Socket.<anonymous> (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
2016-03-15T13:52:53.785305248Z           at emitOne (events.js:77:13)
2016-03-15T13:52:53.785312204Z           at Socket.emit (events.js:169:7)
2016-03-15T13:52:53.785319072Z           at readableAddChunk (_stream_readable.js:146:16)
2016-03-15T13:52:53.785325948Z           at Socket.Readable.push (_stream_readable.js:110:10)
2016-03-15T13:52:53.785332624Z           at TCP.onread (net.js:529:20)
2016-03-15T13:52:53.785339563Z     """
2016-03-15T13:52:53.785347455Z   details:
2016-03-15T13:52:53.785354080Z     """
2016-03-15T13:52:53.785361025Z       Invalid attributes sent to undefined:
2016-03-15T13:52:53.785367738Z        • ipAddress
2016-03-15T13:52:53.785374627Z          • A record with that `ipAddress` already exists (`null`).
2016-03-15T13:52:53.785381715Z
2016-03-15T13:52:53.785388293Z     """
2016-03-15T13:52:53.785394860Z   reason:            1 attribute is invalid
2016-03-15T13:52:53.785401674Z   status:            400
2016-03-15T13:52:53.785408288Z path:  /profiles
2016-03-15T13:52:53.791741346Z [info] [2016-03-15T13:52:53.786Z] [on-syslog] [Syslog] [Server] ipxe: Could not boot image: Input/output error (http://ipxe.org/1d0c6439)
2016-03-15T13:52:53.791769946Z  -> /lib/app.js:65
2016-03-15T13:52:53.791780311Z facility: 0
2016-03-15T13:52:53.791788222Z priority: 6
2016-03-15T13:52:53.794787821Z [debug] [2016-03-15T13:52:53.790Z] [on-http] [Http.Server] [Server] http: GET 400 108.835 - /api/common/profiles?macs=2c%3A60%3A0c%3A83%3Af4%3A47&macs=2c%3A60%3A0c%3A83%3Af4%3A48&macs=90%3Ae2%3Aba%3A84%3A2a%3Ac8&macs=90%3Ae2%3Aba%3A84%3A2a%3Ac9
2016-03-15T13:52:53.794818405Z  -> /lib/services/http-service.js:298
2016-03-15T13:52:53.794828838Z ipAddress: 172.31.128.2
2016-03-15T13:52:54.300273093Z [2016-03-15 13:52:54,300][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
2016-03-15T13:52:54.346869440Z [2016-03-15 13:52:54,346][INFO ][cluster.metadata         ] [Blitziana] [logstash-2016.03.15] update_mapping [logs]
```

**Comment by rolandpoulter** [comment]
Here is a potential workaround if you encounter this issue using RackHD and Docker:

1) Open a shell to the mongo container:

```
$ docker exec -it <mongo-container-id> /bin/sh
```

2) Fix the indexes on the lookups collection:

```
$ mongo rackhd # or "mongo pxe" for non-docker users
> db.lookups.dropIndex(‘ipAddress’)
> db.lookups.createIndex({macAddress: 1, ipAddress: 1}, {unique: true})
> exit
```

Still need to verify this.

**Comment by anhou** [comment]
@rolandpoulter   it looks this issue is the same with https://github.com/RackHD/RackHD/issues/121 and https://github.com/RackHD/RackHD/issues/122 ?

**Comment by rolandpoulter** [comment]
@anhou no this is a new issue. It is related but not the same. This is specifically about a duplicate key error for lookups that have a `null` `ipAddress`.
