### ISSUE TITLE
invoking PowerOff call resulting in traceback in on-taskgraph

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#142]
from maithri (@MaithriAjjampura) in the Slack channel:

Invoked the calls to create a node and then run the PowerOff workflow against that node. That failed, with the following traceback in the on-taskgraph logs:

```
TypeError: Cannot call method 'powerStatus' of null
    at /home/vagrant/src/on-tasks/lib/services/obm-service.js:153:44
    at tryCatcher (/home/vagrant/src/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:507:31
    at Promise._settlePromiseAt (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:15:14
    at process._tickDomainCallback (node.js:459:13)
```

The node in question, when returned from `/api/1.1/nodes/[nodeid]`:

```
{
   "autoDiscover": false,
   "catalogs": [],
   "createdAt": "2016-02-17T22:48:03.017Z",
   "id": "56c4f8a32b765c4848208dff",
   "identifiers": [
       "ec:f4:bb:d9:b1:00",
       "ec:f4:bb:d9:b1:02",
       "ec:f4:bb:d9:b1:04",
       "ec:f4:bb:d9:b1:05"
   ],
   "name": "ec:f4:bb:d9:b1:00,ec:f4:bb:d9:b1:02,ec:f4:bb:d9:b1:04,ec:f4:bb:d9:b1:05",
   "obmSettings": [
       {
           "config": {
               "host": "10.10.1.3",
               "pass": "test",
               "user": "root"
           },
           "service": "ipmi-obm-service"
       }
   ],
   "relations": [
       {
           "relationType": "enclosedBy",
           "targets": [
               "56c5de2003dd5b4248dba5f7"
           ]
       }
   ],
   "sku": null,
   "type": "compute",
   "updatedAt": "2016-03-15T15:35:58.812Z",
   "workflows": []
}
```

**Comment by anhou** [comment]
@MaithriAjjampura  I have a quick validation that if "password" is set to 'pass', there will be 'powerStatus' of 'null' error in log. so just correct 'pass' to 'password' in obmSettings and go ahead for your works. 
But anyway, it should be a issue that the log shouldn't  report 'powerStatus of null' which is related with 'password' key. it's a problem need to be fixed

**Comment by MaithriAjjampura** [comment]
@anhou , I changed it to password in obmsettings and the node returns this 
{
    "autoDiscover": false,
    "catalogs": [],
    "createdAt": "2016-02-17T22:48:03.017Z",
    "id": "56c4f8a32b765c4848208dff",
    "identifiers": [
        "ec:f4:bb:d9:b1:00",
        "ec:f4:bb:d9:b1:02",
        "ec:f4:bb:d9:b1:04",
        "ec:f4:bb:d9:b1:05"
    ],
    "name": "ec:f4:bb:d9:b1:00,ec:f4:bb:d9:b1:02,ec:f4:bb:d9:b1:04,ec:f4:bb:d9:b1:05",
    "obmSettings": [
        {
            "config": {
                "host": "10.10.1.3",
                "password": "REDACTED",
                "user": "root"
            },
            "service": "ipmi-obm-service"
        }
    ],
    "relations": [
        {
            "relationType": "enclosedBy",
            "targets": [
                "56c5de2003dd5b4248dba5f7"
            ]
        }
    ],
    "sku": null,
    "type": "compute",
    "updatedAt": "2016-03-21T15:03:07.565Z",
    "workflows": []
}
I executed the workflow, and this is the response I am getting back when I tried this:
http://192.168.1.203:8080/api/1.1/nodes/56c4f8a32b765c4848208dff/workflows | python -mjson.tool 
{
        "_status": "failed",
        "context": {
            "graphId": "474b29d9-9d19-4900-bd35-d5950bfd293b",
            "target": "56c4f8a32b765c4848208dff"
        },
        "createdAt": "2016-03-18T18:15:35.292Z",
        "definition": {
            "friendlyName": "PowerOff Node",
            "injectableName": "Graph.PowerOff.Node",
            "options": {},
            "tasks": [
                {
                    "label": "poweroff",
                    "taskName": "Task.Obm.Node.PowerOff"
                }
            ]
        },
        "domain": "default",
        "id": "56ec45c7df1b451b412c800e",
        "injectableName": "Graph.PowerOff.Node",
        "instanceId": "474b29d9-9d19-4900-bd35-d5950bfd293b",
        "logContext": {
            "graphInstance": "474b29d9-9d19-4900-bd35-d5950bfd293b",
            "graphName": "PowerOff Node",
            "id": "56c4f8a32b765c4848208dff"
        },
        "name": "PowerOff Node",
        "node": "56c4f8a32b765c4848208dff",
        "serviceGraph": null,
        "tasks": {
            "2df33214-5c41-4765-a29b-047dcbb427a0": {
                "error": "TypeError: Cannot call method 'powerStatus' of null\n    at /home/vagrant/src/on-tasks/lib/services/obm-service.js:153:44\n    at tryCatcher (/home/vagrant/src/on-core/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:581:18)\n    at Promise._settlePromises (/home/vagrant/src/on-core/node_modules/bluebird/js/main/promise.js:697:14)\n    at Async._drainQueue (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/home/vagrant/src/on-core/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickDomainCallback (node.js:459:13)",
                "friendlyName": "Power Off Node",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Obm.Node",
                "injectableName": "Task.Obm.Node.PowerOff",
                "instanceId": "2df33214-5c41-4765-a29b-047dcbb427a0",
                "name": "Task.Obm.Node.PowerOff",
                "options": {
                    "action": "powerOff",
                    "obmServiceName": "ipmi-obm-service"
                },
                "properties": {
                    "power": {}
                },
                "runJob": "Job.Obm.Node",
                "state": "failed",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {}
            }
        },
        "updatedAt": "2016-03-18T18:15:35.359Z"
    }
This is on Dell server R630

**Comment by yyscamper** [comment]
@MaithriAjjampura:  `/api/1.1/nodes/<identifier>/workflows` will return **all** history workflows that have been run for the target node, not only the last workflow. I see you updated  the obm setting in `2016-03-21T15:03:07.565Z`, but this workflow result was logged at `2016-03-18T18:15:35.359Z`, they don't match.

**Comment by yyscamper** [comment]
This should be the root case of the called on null object: https://github.com/RackHD/on-tasks/blob/master/lib/services/base-obm-service.js#L148, the function [`validateAndSanitize`](https://github.com/RackHD/on-tasks/blob/master/lib/services/base-obm-service.js#L95) will fail to validate the requiredKeys becase `password` is in the required for ipmi-obm-service (https://github.com/RackHD/on-tasks/blob/master/lib%2Fservices%2Fipmi-obm-service.js#L16) , so creating obm service return a null object not to throw error. 

So there should be a minor fix on this

**Comment by MaithriAjjampura** [comment]
Thank you @yyscamper and @anhou . so when I changed the obm settings, I just ran workflow and it did not take affect. But when I  posted the task again to workflow curl -X POST 192.168.1.203:8080/api/1.1/nodes/<id>/workflows?name=Graph.PowerOff.Node, I could successfully power off the compute node. now the workflow for the node contains power off node details twice.

**Comment by yyscamper** [comment]
@MaithriAjjampura : is their any response code that returned from API after your first time to run workflow?

**Comment by heckj** [comment]
@MaithriAjjampura are you still seeing this issue?

@yyscamper did we put in a fix to make understanding the underlying cause for this issue easier?
