### ISSUE TITLE
CI Functional Test: FAIL: Testing PUT:/workflowTasks

### ISSUE THREAD

**Issue by amymullins** [RackHD/RackHD#170]
Seeing roughly 12% failures during CI Functional Test.  After preliminary review by @benbp , "The test submits a graph definition, then retrieves all graph definitions, and compares the last definition in the result array against the submitted definition. But the result array isn’t sorted, so there’s no guarantee that the results will be in the right order every time."

Error reported: 
======================================================================
FAIL: Testing PUT:/workflowTasks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v1_1/workflowTasks_tests.py", line 88, in test_workflowTasks_put
    assert_equal(readFriendlyName,self.workflowTaskDict.get('friendlyName'))
AssertionError: Soft Reset Node != fn_1
-------------------- >> begin captured logging << --------------------
tests.api.v1_1.workflowTasks_tests: INFO: Adding workflow task: 
tests.api.v1_1.workflowTasks_tests: INFO: {
    "friendlyName": "fn_1",
    "implementsTask": "im_1",
    "injectableName": "in_1",
    "options": {},
    "properties": {}

**Comment by amymullins** [comment]
if you set the pull request message to read:
 resolves RackHD/RackHD#170
 then when this is merged, it will close the github bug
