### ISSUE TITLE
CI Functional Test: Error with "test_node_workflows_del_active" and "pollers_data_get"

### ISSUE THREAD

**Issue by amymullins** [RackHD/RackHD#173]
Seeing roughly 3.5% failures during CI Functional Test. After preliminary review by @benbp , "these seem like legitimate bugs." Error being reported: 

ERROR: Testing node DELETE:id/workflows/active
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v1_1/nodes_tests.py", line 376, in test_node_workflows_del_active
    raise e
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Length': '55', 'X-Powered-By': 'Express', 'Connection': 'keep-alive', 'ETag': 'W/"37-zOsyQq00pF/MeBunE+SFSg"', 'Date': 'Fri, 08 Apr 2016 18:47:34 GMT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {"message":"Failed to cancel 5707fcc2289fd320a9674c34"}

-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /api/1.1/nodes
urllib3.connectionpool: INFO: Starting new HTTP connection (11): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Test GET:/api/2.0/pollers/:identifier/data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v2_0/pollers_tests.py", line 157, in pollers_data_get
    assert_false(poller.get('lastFinished', False))
AssertionError: Condition was True.

**Comment by amymullins** [comment]
As of 4/27/16, frequency of this issue has dropped to 0.6% (1 failing case out of the sample of 159 runs)

**Comment by amymullins** [comment]
Closing this issue.  As of 5/18/16, frequency is 0% and no longer seeing these failures in CI.
