### ISSUE TITLE
Passive switch discovery fails with AssertionError: number ([number]) required

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#177]
We are getting an exception when trying to discover a switch (workflow fails) and it appears that after that, we get no data for the switch.

```
 -> /lib/task-scheduler.js:471
createdAt:      Wed Apr 13 2016 15:08:48 GMT+0000 (UTC)
name:           Switch Discovery
tasks:
  93712c13-e779-4fc8-8281-6a669c4e9a0b:
    friendlyName:     Snmp Discovery Collect
    ignoreFailure:    false
    implementsTask:   Task.Base.Snmp.Collect
    injectableName:   Task.Snmp.Collect.Discovery
    instanceId:       93712c13-e779-4fc8-8281-6a669c4e9a0b
    name:             Task.Snmp.Collect.Discovery
    options:
      snmpQueryType: bulkwalk
      oids:
        - 1
    properties:

    runJob:           Job.Snmp.Collect
    state:            failed
    terminalOnStates:
      - succeeded
      - timeout
      - cancelled
      - failed
    waitingOn:
      82c38e43-4942-4fb2-92bd-a80a19201fdc: succeeded
  af3a7bb7-8d19-49e3-9ef6-c0ea16fc279c:
    friendlyName:     Snmp Node Update
    ignoreFailure:    false
    implementsTask:   Task.Base.Node.Update
    injectableName:   Task.Snmp.Node.Update
    instanceId:       af3a7bb7-8d19-49e3-9ef6-c0ea16fc279c
    name:             Task.Snmp.Node.Update
    options:

    properties:

    runJob:           Job.Snmp.Node.Update
    state:            failed
    terminalOnStates:
      - succeeded
      - timeout
      - cancelled
      - failed
    waitingOn:
      ed3513ec-215e-4472-88f8-1b651af40249: succeeded
  82c38e43-4942-4fb2-92bd-a80a19201fdc:
    error:
      """
        AssertionError: number ([number]) required
            at AssertService.(anonymous function) [as optionalArrayOfNumber] (/var/renasar/on-taskgraph/node_modules/on-core/lib/common/assert.js:30:28)
            at new ChildProcess (/var/renasar/on-taskgraph/node_modules/on-core/lib/common/child-process.js:52:16)
            at SnmpTool.SnmpFactory.SnmpTool.runCommand (/var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/net-snmp-tool.js:49:28)
            at SnmpTool.SnmpFactory.SnmpTool.walk (/var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/net-snmp-tool.js:54:21)
            at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/net-snmp-tool.js:115:24
            at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
            at MappingPromiseArray._promiseFulfilled (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/map.js:56:38)
            at MappingPromiseArray.init [as _init$] (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise_array.js:92:18)
            at MappingPromiseArray.init (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/map.js:29:23)
            at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:128:12)
            at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
            at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
            at process._tickDomainCallback (node.js:459:13)
      """
    friendlyName:     Ping Snmp
    ignoreFailure:    false
    implementsTask:   Task.Base.Snmp.Collect
    injectableName:   Task.Snmp.Ping
    instanceId:       82c38e43-4942-4fb2-92bd-a80a19201fdc
    name:             Task.Snmp.Ping
    options:
      oids:
        - SNMPv2-MIB::sysDescr
    properties:

    runJob:           Job.Snmp.Collect
    state:            failed
    terminalOnStates:
      - timeout
      - cancelled
      - failed
    waitingOn:

  e1a4d9e4-2c80-471d-86f7-65f2261c1cf8:
    friendlyName:     Create Default Pollers
    ignoreFailure:    false
    implementsTask:   Task.Base.Pollers.CreateDefault
    injectableName:   Task.Pollers.CreateDefault
    instanceId:       e1a4d9e4-2c80-471d-86f7-65f2261c1cf8
    name:             Task.Pollers.CreateDefault
    options:
      nodeId:  570e61003ed2ae3f08b3f9f2
      pollers:
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-interface-bandwidth-utilization
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-interface-state
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-processor-load
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-memory-usage
    properties:
    runJob:           Job.Pollers.CreateDefault
    state:            failed
    terminalOnStates:
      - succeeded
      - timeout
      - cancelled
      - failed
    waitingOn:
      ed3513ec-215e-4472-88f8-1b651af40249: succeeded
  ed3513ec-215e-4472-88f8-1b651af40249:
    friendlyName:     Catalog Snmp
    ignoreFailure:    false
    implementsTask:   Task.Base.Snmp.Catalog
    injectableName:   Task.Snmp.Catalog
    instanceId:       ed3513ec-215e-4472-88f8-1b651af40249
    name:             Task.Snmp.Catalog
    options:

    properties:

    runJob:           Job.Snmp.Catalog
    state:            failed
    terminalOnStates:
      - timeout
      - cancelled
      - failed
    waitingOn:
      82c38e43-4942-4fb2-92bd-a80a19201fdc: succeeded
updatedAt:      Wed Apr 13 2016 15:08:48 GMT+0000 (UTC)
injectableName: Graph.Switch.Discovery
_id:
  _bsontype: ObjectID
  id:        W^Na^@Å=)^PvXa%
schedulerId:    9c68fbf5-f5fa-4d23-a4f3-0223801c113f
definition:
  friendlyName:   Switch Discovery
  injectableName: Graph.Switch.Discovery
  options:
    defaults:
      nodeId:    570e61003ed2ae3f08b3f9f2
      host:      172.18.1.103
      community: [REDACTED]
    create-switch-snmp-pollers:
      pollers:
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-interface-bandwidth-utilization
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-interface-state
        -
          type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-processor-load
        -
          type:         snmp
         type:         snmp
          pollInterval: 60000
          config:
            metric: snmp-memory-usage
  tasks:
    -
      label:    ping-host
      taskName: Task.Snmp.Ping
    -
      label:    collect-snmp
      taskName: Task.Snmp.Collect.Discovery
      waitOn:
        82c38e43-4942-4fb2-92bd-a80a19201fdc: succeeded
    -
      label:    catalog-snmp
      taskName: Task.Snmp.Catalog
      waitOn:
        82c38e43-4942-4fb2-92bd-a80a19201fdc: succeeded
    -
      label:    create-switch-snmp-pollers
      taskName: Task.Pollers.CreateDefault
      waitOn:
        ed3513ec-215e-4472-88f8-1b651af40249: succeeded
    -
      label:    update-node-name
      taskName: Task.Snmp.Node.Update
      waitOn:
        ed3513ec-215e-4472-88f8-1b651af40249: succeeded
logContext:
  graphInstance: 88cc5ecd-5e4e-4cb4-a620-2985d2276bd1
          graphName:     Switch Discovery
          id:            570e61003ed2ae3f08b3f9f2
        serviceGraph:   null
        node:
          _bsontype: ObjectID
          id:        W^Na^@>Ò®?^H³ùò
        context:
          graphId: 88cc5ecd-5e4e-4cb4-a620-2985d2276bd1
          target:  570e61003ed2ae3f08b3f9f2
        instanceId:     88cc5ecd-5e4e-4cb4-a620-2985d2276bd1
        domain:         default
        _status:        failed
        [debug] [2016-04-13T15:08:50.450Z] [on-taskgraph] [Services.ErrorPublisher] [Server] Event Loop Blocked
         -> /node_modules/on-core/lib/services/error-publisher.js:85
        host:     ora
        name:     on-taskgraph
        severity: debug
```

**Comment by johren** [comment]
Example payload:

```
{
                    "type":"switch",
                    "name":"null",
                    "autoDiscover":True,
                    "snmpSettings":{
                        "host": "172.18.1.44",
                        "community":"onrack",
                    }
}
```

**Comment by johren** [comment]
@iceiilin

**Comment by johren** [comment]
This is being tracked internally with ODR-626.
Logs at https://web.hwimo.lab.emc.com/qa/log/bug_logs/ODR-626/

This is currently blocking us on three work items.

**Comment by benbp** [comment]
CC: @VulpesArtificem 
@rolandpoulter I heard a rumor you were working on this??

**Comment by rolandpoulter** [comment]
I think I did say I would fix this, anyways the PR is now up.
