### ISSUE TITLE
failed graph-from-SKU definition error - traceback in installOS workflow

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#178]
Working with InfraSim (quanta_d51) - currently has an issue where in a vagrant deployment, it's returning an incorrect BMC settings IP address and mac-address (wrong NIC). The graph that I'm triggering form this SKU definition is intended to:

* set up the OBM settings from the catalogs
* install CoreOS

The example graph I'm working on is:
```
{
    "friendlyName": "vQuanta D51 Default Install CoreOS",
    "injectableName": "Graph.DefaultVQuanta.InstallCoreOS",
    "tasks": [
        {
            "label": "create-ipmi-obm-settings",
            "taskDefinition": {
                "friendlyName": "Create IPMI OBM settings",
                "injectableName": "Task.Obm.Ipmi.CreateSettings",
                "implementsTask": "Task.Base.Obm.Ipmi.CreateSettings",
                "options": {
                    "ipmichannel": null,
                    "user": "admin",
                    "password": "admin"
                },
                "properties": {
                }
            }
        },
        {
            "label": "install-coreos",
            "taskName": "Task.Os.Install.CoreOS"
        }
    ]
}
```

When the create-ipmi-obm-setting fails, it has a good and useful answer:
```
"error": "Error: Command failed: Error: Unable to establish IPMI v2 / RMCP+ session

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)",
```

The error for the other task (which I accidentally left concurrent) has a massive traceback called "TaskCancellationError" - cause when I think the task was attempting to be cancelled:

```
"error": "TaskCancellationError
    at Task.cancel (/home/vagrant/src/on-taskgraph/node_modules/on-tasks/lib/task.js:341:26)
    at Rx.Observable.just.map.filter.tap.flatMap.map.taskId (/home/vagrant/src/on-taskgraph/lib/task-runner.js:195:51)
    at tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2096:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:4587:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5669:29)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5283:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)",
```

so I *think* the cancelled task mechanism had a failure, but was otherwise hidden by the failed outer workflow.

**Comment by heckj** [comment]
full output of `curl http://localhost:9090/api/1.1/nodes/570ec21a1866056d07cc4b11/workflows`:

```
[
    {
        "_status": "succeeded",
        "context": {
            "graphId": "028476ba-2d2c-4c24-a67d-f33f7e94e34b",
            "target": "570ec21a1866056d07cc4b11"
        },
        "createdAt": "2016-04-13T22:03:06.929Z",
        "definition": {
            "friendlyName": "Discovery",
            "injectableName": "Graph.Discovery",
            "options": {
                "bootstrap-ubuntu": {
                    "triggerGroup": "bootstrap"
                },
                "finish-bootstrap-trigger": {
                    "triggerGroup": "bootstrap"
                },
                "instanceId": "028476ba-2d2c-4c24-a67d-f33f7e94e34b",
                "target": "570ec21a1866056d07cc4b11"
            },
            "tasks": [
                {
                    "label": "bootstrap-ubuntu",
                    "taskName": "Task.Linux.Bootstrap.Ubuntu"
                },
                {
                    "label": "catalog-dmi",
                    "taskName": "Task.Catalog.dmi"
                },
                {
                    "label": "catalog-ohai",
                    "taskName": "Task.Catalog.ohai",
                    "waitOn": {
                        "7ccbab43-e6ba-4ecc-b46f-a340d4597942": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-bmc",
                    "taskName": "Task.Catalog.bmc",
                    "waitOn": {
                        "46c11648-51f5-425a-b8db-cffb4d533ee5": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-lsall",
                    "taskName": "Task.Catalog.lsall",
                    "waitOn": {
                        "a62d9b8d-aa93-47a0-bb60-74537386b205": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-megaraid",
                    "taskName": "Task.Catalog.megaraid",
                    "waitOn": {
                        "438c73fe-9cba-4dcb-9960-3d3e205c8aee": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-smart",
                    "taskName": "Task.Catalog.smart",
                    "waitOn": {
                        "7ac2f900-1307-41c4-a5aa-1160bb6ddcf2": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-driveid",
                    "taskName": "Task.Catalog.Drive.Id",
                    "waitOn": {
                        "8b668c8e-8e95-4e1a-b92c-df9b0e6eafc1": [
                            "finished"
                        ]
                    }
                },
                {
                    "ignoreFailure": true,
                    "label": "catalog-lldp",
                    "taskName": "Task.Catalog.LLDP",
                    "waitOn": {
                        "fb4cc151-6539-4104-a845-64195a792ebd": [
                            "finished"
                        ]
                    }
                },
                {
                    "label": "shell-reboot",
                    "taskName": "Task.ProcShellReboot",
                    "waitOn": {
                        "975a646f-a58c-4730-806e-113cd28ba07e": [
                            "finished"
                        ]
                    }
                },
                {
                    "label": "finish-bootstrap-trigger",
                    "taskName": "Task.Trigger.Send.Finish",
                    "waitOn": {
                        "975a646f-a58c-4730-806e-113cd28ba07e": [
                            "finished"
                        ]
                    }
                }
            ]
        },
        "domain": "default",
        "id": "570ec21a365d256069363e52",
        "injectableName": "Graph.Discovery",
        "instanceId": "028476ba-2d2c-4c24-a67d-f33f7e94e34b",
        "logContext": {
            "graphInstance": "028476ba-2d2c-4c24-a67d-f33f7e94e34b",
            "graphName": "Discovery",
            "id": "570ec21a1866056d07cc4b11"
        },
        "name": "Discovery",
        "node": "570ec21a1866056d07cc4b11",
        "serviceGraph": null,
        "tasks": {
            "438c73fe-9cba-4dcb-9960-3d3e205c8aee": {
                "friendlyName": "Catalog lsall",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.lsall",
                "instanceId": "438c73fe-9cba-4dcb-9960-3d3e205c8aee",
                "name": "Task.Catalog.lsall",
                "options": {
                    "commands": [
                        "sudo lspci -nn -vmm",
                        "sudo lshw -json",
                        "sudo lsblk -o KNAME,TYPE,ROTA; echo BREAK; sudo lsscsi --size"
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "lsall"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "a62d9b8d-aa93-47a0-bb60-74537386b205": [
                        "finished"
                    ]
                }
            },
            "46c11648-51f5-425a-b8db-cffb4d533ee5": {
                "friendlyName": "Catalog ohai",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.ohai",
                "instanceId": "46c11648-51f5-425a-b8db-cffb4d533ee5",
                "name": "Task.Catalog.ohai",
                "options": {
                    "commands": [
                        "sudo ohai --directory /etc/ohai/plugins"
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "ohai"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "7ccbab43-e6ba-4ecc-b46f-a340d4597942": [
                        "finished"
                    ]
                }
            },
            "7ac2f900-1307-41c4-a5aa-1160bb6ddcf2": {
                "friendlyName": "Catalog megaraid",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.megaraid",
                "instanceId": "7ac2f900-1307-41c4-a5aa-1160bb6ddcf2",
                "name": "Task.Catalog.megaraid",
                "options": {
                    "adapter": "0",
                    "commands": [
                        "sudo /opt/MegaRAID/storcli/storcli64 /c{{ options.adapter }} show all J",
                        "sudo /opt/MegaRAID/storcli/storcli64 show ctrlcount J",
                        "sudo /opt/MegaRAID/storcli/storcli64 /c{{ options.adapter }} /eall /sall show all J",
                        "sudo /opt/MegaRAID/storcli/storcli64 /c{{ options.adapter }} /vall show all J"
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "megaraid"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "438c73fe-9cba-4dcb-9960-3d3e205c8aee": [
                        "finished"
                    ]
                }
            },
            "7c7cbde7-309f-4f19-beb2-2a2e71ef8134": {
                "friendlyName": "Reboot Node via proc",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.ShellReboot",
                "injectableName": "Task.ProcShellReboot",
                "instanceId": "7c7cbde7-309f-4f19-beb2-2a2e71ef8134",
                "name": "Task.ProcShellReboot",
                "options": {
                    "rebootCode": 1
                },
                "properties": {
                    "power": {}
                },
                "runJob": "Job.Linux.ShellReboot",
                "state": "succeeded",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {
                    "975a646f-a58c-4730-806e-113cd28ba07e": [
                        "finished"
                    ]
                }
            },
            "7ccbab43-e6ba-4ecc-b46f-a340d4597942": {
                "friendlyName": "Catalog dmi",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.dmi",
                "instanceId": "7ccbab43-e6ba-4ecc-b46f-a340d4597942",
                "name": "Task.Catalog.dmi",
                "options": {
                    "commands": [
                        "sudo dmidecode"
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "dmi"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {}
            },
            "7dcde421-e6c7-4c28-af6a-ff8fce52be01": {
                "friendlyName": "Send Finish Trigger",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Trigger",
                "injectableName": "Task.Trigger.Send.Finish",
                "instanceId": "7dcde421-e6c7-4c28-af6a-ff8fce52be01",
                "name": "Task.Trigger.Send.Finish",
                "options": {
                    "triggerGroup": "bootstrap",
                    "triggerMode": "send",
                    "triggerType": "finish"
                },
                "properties": {},
                "runJob": "Job.Trigger",
                "state": "succeeded",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {
                    "975a646f-a58c-4730-806e-113cd28ba07e": [
                        "finished"
                    ]
                }
            },
            "8b668c8e-8e95-4e1a-b92c-df9b0e6eafc1": {
                "friendlyName": "Catalog S.M.A.R.T",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.smart",
                "instanceId": "8b668c8e-8e95-4e1a-b92c-df9b0e6eafc1",
                "name": "Task.Catalog.smart",
                "options": {
                    "commands": [
                        {
                            "command": "sudo bash get_smart.sh",
                            "downloadUrl": "/api/1.1/templates/get_smart.sh"
                        }
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "smart"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "7ac2f900-1307-41c4-a5aa-1160bb6ddcf2": [
                        "finished"
                    ]
                }
            },
            "91bafafe-8895-4174-9910-97fe1d68f696": {
                "friendlyName": "Bootstrap Ubuntu",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Linux.Bootstrap",
                "injectableName": "Task.Linux.Bootstrap.Ubuntu",
                "instanceId": "91bafafe-8895-4174-9910-97fe1d68f696",
                "name": "Task.Linux.Bootstrap.Ubuntu",
                "options": {
                    "basefs": "common/base.trusty.3.16.0-25-generic.squashfs.img",
                    "comport": "ttyS0",
                    "initrdFile": "initrd.img-3.16.0-25-generic",
                    "initrdUri": "{{ api.server }}/common/{{ options.initrdFile }}",
                    "kernelFile": "vmlinuz-3.16.0-25-generic",
                    "kernelUri": "{{ api.server }}/common/{{ options.kernelFile }}",
                    "overlayfs": "common/discovery.overlay.cpio.gz",
                    "profile": "linux.ipxe",
                    "triggerGroup": "bootstrap"
                },
                "properties": {
                    "os": {
                        "linux": {
                            "distribution": "ubuntu",
                            "kernel": "3.16.0-25-generic",
                            "release": "trusty",
                            "type": "microkernel"
                        }
                    }
                },
                "runJob": "Job.Linux.Bootstrap",
                "state": "succeeded",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {}
            },
            "975a646f-a58c-4730-806e-113cd28ba07e": {
                "friendlyName": "Catalog LLDP",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.LLDP",
                "instanceId": "975a646f-a58c-4730-806e-113cd28ba07e",
                "name": "Task.Catalog.LLDP",
                "options": {
                    "commands": [
                        "sudo /usr/sbin/lldpcli show neighbor -f keyvalue"
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "lldp"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "fb4cc151-6539-4104-a845-64195a792ebd": [
                        "finished"
                    ]
                }
            },
            "a62d9b8d-aa93-47a0-bb60-74537386b205": {
                "friendlyName": "Catalog bmc",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.bmc",
                "instanceId": "a62d9b8d-aa93-47a0-bb60-74537386b205",
                "name": "Task.Catalog.bmc",
                "options": {
                    "commands": [
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print"
                        },
                        "sudo ipmitool sel",
                        "sudo ipmitool sel list -c",
                        "sudo ipmitool mc info",
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 1"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 1"
                        },
                        "sudo ipmitool fru",
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 2"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 2"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 2"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 3"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 3"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 3"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 4"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 4"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 4"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 5"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 5"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 5"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 6"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 6"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 6"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 7"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 7"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 7"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 8"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 8"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 8"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 9"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 9"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 9"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 10"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 10"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 10"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 11"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 11"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 11"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 12"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 12"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 12"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 13"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 13"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 13"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 14"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 14"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 14"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool lan print 15"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool user summary 15"
                        },
                        {
                            "acceptedResponseCodes": [
                                1
                            ],
                            "command": "sudo ipmitool -c user list 15"
                        }
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "bmc"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "46c11648-51f5-425a-b8db-cffb4d533ee5": [
                        "finished"
                    ]
                }
            },
            "fb4cc151-6539-4104-a845-64195a792ebd": {
                "friendlyName": "Catalog Drive IDs",
                "ignoreFailure": true,
                "implementsTask": "Task.Base.Linux.Catalog",
                "injectableName": "Task.Catalog.Drive.Id",
                "instanceId": "fb4cc151-6539-4104-a845-64195a792ebd",
                "name": "Task.Catalog.Drive.Id",
                "options": {
                    "commands": [
                        {
                            "command": "sudo node get_driveid.js",
                            "downloadUrl": "/api/1.1/templates/get_driveid.js"
                        }
                    ]
                },
                "properties": {
                    "catalog": {
                        "type": "driveId"
                    }
                },
                "runJob": "Job.Linux.Catalog",
                "state": "succeeded",
                "terminalOnStates": [],
                "waitingOn": {
                    "8b668c8e-8e95-4e1a-b92c-df9b0e6eafc1": [
                        "finished"
                    ]
                }
            }
        },
        "updatedAt": "2016-04-13T22:06:37.882Z"
    },
    {
        "_status": "failed",
        "context": {
            "graphId": "82392609-01ba-4364-b1fd-2453fa94bb71",
            "target": "570ec21a1866056d07cc4b11"
        },
        "createdAt": "2016-04-13T22:06:38.001Z",
        "definition": {
            "friendlyName": "vQuanta D51 Default Install CoreOS",
            "injectableName": "Graph.DefaultVQuanta.InstallCoreOS",
            "options": {},
            "tasks": [
                {
                    "label": "create-ipmi-obm-settings",
                    "taskDefinition": {
                        "friendlyName": "Create IPMI OBM settings",
                        "implementsTask": "Task.Base.Obm.Ipmi.CreateSettings",
                        "injectableName": "Task.Obm.Ipmi.CreateSettings",
                        "options": {
                            "ipmichannel": null,
                            "password": "admin",
                            "user": "admin"
                        },
                        "properties": {
                            "obm": {
                                "type": "ipmi"
                            }
                        }
                    }
                },
                {
                    "label": "install-coreos",
                    "taskName": "Task.Os.Install.CoreOS"
                }
            ]
        },
        "domain": "default",
        "id": "570ec2ee365d256069363e53",
        "injectableName": "Graph.DefaultVQuanta.InstallCoreOS",
        "instanceId": "82392609-01ba-4364-b1fd-2453fa94bb71",
        "logContext": {
            "graphInstance": "82392609-01ba-4364-b1fd-2453fa94bb71",
            "graphName": "vQuanta D51 Default Install CoreOS",
            "id": "570ec21a1866056d07cc4b11"
        },
        "name": "vQuanta D51 Default Install CoreOS",
        "node": "570ec21a1866056d07cc4b11",
        "serviceGraph": null,
        "tasks": {
            "e8fe6c53-d586-4d24-b2eb-3c8613efcbb2": {
                "error": "TaskCancellationError\n    at Task.cancel (/home/vagrant/src/on-taskgraph/node_modules/on-tasks/lib/task.js:341:26)\n    at Rx.Observable.just.map.filter.tap.flatMap.map.taskId (/home/vagrant/src/on-taskgraph/lib/task-runner.js:195:51)\n    at tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)\n    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2096:43)\n    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)\n    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)\n    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:4587:14)\n    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)\n    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)\n    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5669:29)\n    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)\n    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)\n    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5283:14)\n    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)\n    at InnerObserver.tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)\n    at AutoDetachObserverPrototype.next (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)",
                "friendlyName": "Install CoreOS",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Os.Install",
                "injectableName": "Task.Os.Install.CoreOS",
                "instanceId": "e8fe6c53-d586-4d24-b2eb-3c8613efcbb2",
                "name": "Task.Os.Install.CoreOS",
                "options": {
                    "completionUri": "pxe-cloud-config.yml",
                    "comport": "ttyS0",
                    "hostname": "coreos-node",
                    "installDisk": "/dev/sda",
                    "profile": "install-coreos.ipxe",
                    "repo": "{{api.server}}/coreos",
                    "version": "current"
                },
                "properties": {
                    "os": {
                        "linux": {
                            "distribution": "coreos"
                        },
                        "type": "install"
                    }
                },
                "runJob": "Job.Os.Install",
                "state": "cancelled",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {}
            },
            "f31b8ca5-5914-449e-80ae-f5fb604d2ecb": {
                "error": "Error: Command failed: Error: Unable to establish IPMI v2 / RMCP+ session\n\n    at ChildProcess.exithandler (child_process.js:637:15)\n    at ChildProcess.EventEmitter.emit (events.js:117:20)\n    at maybeClose (child_process.js:743:16)\n    at Socket.<anonymous> (child_process.js:956:11)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Pipe.close (net.js:466:12)",
                "friendlyName": "Create IPMI OBM settings",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Obm.Ipmi.CreateSettings",
                "injectableName": "Task.Obm.Ipmi.CreateSettings",
                "instanceId": "f31b8ca5-5914-449e-80ae-f5fb604d2ecb",
                "name": "Task.Obm.Ipmi.CreateSettings",
                "options": {
                    "ipmichannel": null,
                    "password": "admin",
                    "user": "admin"
                },
                "properties": {
                    "obm": {
                        "type": "ipmi"
                    }
                },
                "runJob": "Job.Obm.Ipmi.CreateSettings",
                "state": "failed",
                "terminalOnStates": [
                    "succeeded",
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {}
            }
        },
        "updatedAt": "2016-04-13T22:09:30.389Z"
    }
]
```

**Comment by heckj** [comment]
@benbp not a high priority, but would you or @VulpesArtificem look over this - is this a bug? or a quirk of how the system is reporting errors when a graph dies while running concurrent tasks?

**Comment by benbp** [comment]
@heckj (as we talked about IRL): intended behavior, as we pass a "cancellation error" to all cancelled tasks (so it's clear they didn't actually fail), but we can probably cut the huge traceback out of that error field for readability.
