### ISSUE TITLE
TypeError running Task.Graph.Run.Discovery of Graph.SKU.Discovery 

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#184]
In our smoke tests, we occasionally hit a case where one of the nodes fails to discover.
I have found the following error in on-taskgraph.log related to the task running on this node.

```
[debug] [2016-04-14T22:10:22.904Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     40014dc0-83fc-4543-85f7-dbd83860fbea
taskId:      d5e56893-79d3-4825-85c6-0adeae301b77
schedulerId: b84f4958-f94b-4176-bbc8-e8ae28b607c4
[error] [2016-04-14T22:10:22.911Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Error fetching task data
 -> /lib/task-runner.js:311
taskRunnerId: 13c7457f-3fe4-490a-84f9-fc762e6f0042
error: 

stack: 
  """
    TypeError: Cannot read property 'instanceId' of undefined
        at /var/renasar/on-taskgraph/node_modules/on-core/lib/workflow/stores/mongo.js:360:31
        at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
        at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
        at Promise._settlePromises (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
        at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
        at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
        at process._tickDomainCallback (node.js:459:13)
  """
```

You can find logs and database dumps at the following links (for each of two recently failed runs):

1801: https://web.hwimo.lab.emc.com/qa/log/QA_test_results/BR_HWIMO/ONRACK_onrack-devel/ora_smoke_test_master.py.ON.stack11-ora.admin/TM_20160414_21_58_30/logs/stack/
1774: https://web.hwimo.lab.emc.com/qa/log/QA_test_results/BR_HWIMO/ONRACK_onrack-devel/ora_smoke_test_master.py.ON.stack11-ora.admin/TM_20160409_12_15_51/logs/stack/

**Comment by johren** [comment]
The graph that failed on the 1801 run.

[failedworkflow.txt](https://github.com/RackHD/RackHD/files/221190/failedworkflow.txt)

**Comment by yyscamper** [comment]
@johren , @benbp 's PR (https://github.com/RackHD/on-tasks/pull/157) may fix this problem, could you please confirm whether your code has already contained this fix?

**Comment by johren** [comment]
The 1801 run did not have this fix.  That fix came in on the 1804 run.

**Comment by johren** [comment]
Since the latest failure did not have the RackHD/on-tasks#157 fix and we have not seen this error since then, I will assume that fixed the issue and close this.  If we see it pop up again, I will reopen.
