### ISSUE TITLE
CI Functional Test Error "workflows_del_active' and "teardown"

### ISSUE THREAD

**Issue by amymullins** [RackHD/RackHD#203]
Seeing roughly 4% failures during CI Functional Test. 

======================================================================
ERROR: Testing node DELETE:id/workflows/active
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v1_1/nodes_tests.py", line 376, in test_node_workflows_del_active
    raise e
ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Length': '55', 'X-Powered-By': 'Express', 'Connection': 'keep-alive', 'ETag': 'W/"37-32h0Iskbe720fGrbE/H+GA"', 'Date': 'Thu, 28 Apr 2016 06:47:20 GMT', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {"message":"Failed to cancel 5721b1f426815a2f8a36d1b9"}

-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine("''",))': /api/1.1/nodes
urllib3.connectionpool: INFO: Starting new HTTP connection (11): localhost
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: restore test environment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/redfish_1_0/session_service_tests.py", line 38, in teardown
    Auth.disable()
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/modules/redfish_auth.py", line 67, in disable
    del config.api_client.default_headers['X-Auth-Token']
KeyError: 'X-Auth-Token'
-------------------- >> begin captured logging << --------------------
modules.redfish_auth: INFO: auth already disabled.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Test GET:/api/2.0/pollers/:identifier/data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v2_0/pollers_tests.py", line 157, in pollers_data_get
    assert_false(poller.get('lastFinished', False))
AssertionError: Condition was True.

**Comment by amymullins** [comment]
Closing this issue.  As of 5/18/16, frequency is 0% and no longer seeing these failures in CI.
