### ISSUE TITLE
ARP polling doesn't work with routed vlans

### ISSUE THREAD

**Issue by ytjohn** [RackHD/RackHD#225]
Last week, https://github.com/RackHD/on-taskgraph/pull/95/ was commited to disable Graph.Service.IscDhcpLeasePoller and replace it with Graph.Service.ArpPoller.  

This breaks anyone using routed vlans (ie, dhcp helper/dhcp forwarding). All IPS will have the switche's mac address in the ARP table. 

You can reverse this behavior by editing `on-taskgraph/lib/graphs/isc-dhcp-poller-service-graph.js` and `on-taskgraph/lib/graphs/arp-poller-service-graph.js` setting serviceGraph to true and false respectively.  However, anytime you update the packages, these files will get overwritten.

We will need to document the workaround, AND as an enhancement, come up with a way to make serviceGraph enablement/disablement persistent across package updates.

**Comment by benbp** [comment]
@jlongever

**Comment by jlongever** [comment]
@ytjohn we've discussed moving the ARP poller out of on-taskgraph and into on-core with a config.json option.  In the meantime could you try running with the ARP poller enabled (DHCP poller disabled) in your environment?

**Comment by amymullins** [comment]
@jlongever had completed the work for moving the ARP poller out of on-taskgraph (story reference: https://www.pivotaltracker.com/projects/1492890/stories/119525347).  

@ytjohn if this has resolved your issue can we consider closing out this github issue?

**Comment by jlongever** [comment]
@amymullins:  @tldavies had changes that moved the DHCP poller to on-dhcp-proxy with a config.json option.  I think that needs to be committed until this issue can be fully resolved.  @benbp and @tldavies please correct me if I'm wrong.

**Comment by jlmcknight** [comment]
I've been doing some testing of this today, and I have a couple issues, hopefully the feedback helps.

During our installs, a node will initially dhcp from a pool of addresses, and we have a process that identifies the node and sets a static dhcp mapping for the real ip.  With the latest onrack packages, this now breaks our boot into OS install because dhcp hands out the new "static" ip, and we get this:

```
[warning] [2016-06-15T17:44:12.921Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.
 -> /lib/message-handler.js:201
```

Also, looking at the arp tables on the host, we have two entries for the mac in question:

```
(vagrant)[root@rackhd01 upstart]# arp -a
? (192.168.37.201) at 08:00:27:bc:f8:88 [ether] on eth1
? (10.0.2.2) at 52:54:00:12:35:02 [ether] on eth0
? (192.168.37.220) at 08:00:27:bc:f8:88 [ether] on eth1
? (10.0.2.3) at 52:54:00:12:35:03 [ether] on eth0
```

192.168.37.220 is the initial IP from the pool and 201 is the static mapping.  I'm guessing that two entries for the same mac in the arp tables is probably at fault, but I need to really dig into the code to make sure.

Also, if I try to disable the arp cache with `"arpCacheEnabled": false` in monorail.json, on-http then falls over when you try to hit the northbound API endpoint with the following error:

```
[debug] [2016-06-15T18:04:58.316Z] [on-http] [Http.Server] [Server] http: GET 500 1.569 - /api/1.1/nodes
 -> /lib/services/http-service.js:321
ipAddress: 127.0.0.1
TypeError: Cannot call method 'then' of undefined
    at LookupService.ipAddressToNodeId (/var/renasar/on-http/node_modules/on-core/lib/services/lookup.js:342:10)
    at httpEventMiddleware (/var/renasar/on-http/lib/services/http-service.js:341:23)
    at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/renasar/on-http/node_modules/express/lib/router/index.js:312:13)
    at /var/renasar/on-http/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/renasar/on-http/node_modules/express/lib/router/index.js:330:12)
    at next (/var/renasar/on-http/node_modules/express/lib/router/index.js:271:10)
    at cors (/var/renasar/on-http/node_modules/cors/lib/index.js:178:7)
    at /var/renasar/on-http/node_modules/cors/lib/index.js:228:17
    at originCallback (/var/renasar/on-http/node_modules/cors/lib/index.js:217:15)
    at /var/renasar/on-http/node_modules/cors/lib/index.js:222:13
    at optionsCallback (/var/renasar/on-http/node_modules/cors/lib/index.js:203:9)
    at /var/renasar/on-http/node_modules/cors/lib/index.js:208:7
    at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/renasar/on-http/node_modules/express/lib/router/index.js:312:13)
    at /var/renasar/on-http/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/renasar/on-http/node_modules/express/lib/router/index.js:330:12)
    at next (/var/renasar/on-http/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/var/renasar/on-http/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/renasar/on-http/node_modules/express/lib/router/index.js:312:13)
    at /var/renasar/on-http/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/renasar/on-http/node_modules/express/lib/router/index.js:330:12)
    at next (/var/renasar/on-http/node_modules/express/lib/router/index.js:271:10)
    at query (/var/renasar/on-http/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/var/renasar/on-http/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/renasar/on-http/node_modules/express/lib/router/index.js:312:13)
    at /var/renasar/on-http/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/renasar/on-http/node_modules/express/lib/router/index.js:330:12)
    at next (/var/renasar/on-http/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/var/renasar/on-http/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/var/renasar/on-http/node_modules/express/lib/application.js:173:10)
    at Server.app (/var/renasar/on-http/node_modules/express/lib/express.js:38:9)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)
```

Please let me know if you need more info.  This is now blocking us in testing the updated proxy handling from https://github.com/RackHD/on-http/pull/274

**Comment by jlongever** [comment]
This PR https://github.com/RackHD/on-core/pull/160 should resolve the the `arpCacheEnabled:false` bug,  need to still return a promise when disabled.

When setting `arpCacheEnabled: false`,  did you edit the `on-taskgraph/lib/graphs/isc-dhcp-poller-service-graph.js` graph and set `serviceGraph: true` ?  There was a request made to move the DHCP poller `serviceGraph` option into the `config.json` that way you could fallback to DHCP polling based on your `config.json` settings (and not edit graph.js files). @benbp @tldavies is there a PR for that?

**Comment by ytjohn** [comment]
This may be semantics to some, but I'd like to not think of ARP polling as primary. I understand that it was implemented for scenarios where the DHCP server exists on another host, but ARP polling is altogether unreliable. It also only works on a flat L2 network; not at all on routed vlans.  As Jamie saw, you can also have a stale arp cache when the IP address changes. You would have to essentially flush the local arp cache each time a node reboots.

```
(vagrant)[root@rackhd01 upstart]# arp -a
? (192.168.37.201) at 08:00:27:bc:f8:88 [ether] on eth1
? (10.0.2.2) at 52:54:00:12:35:02 [ether] on eth0
? (192.168.37.220) at 08:00:27:bc:f8:88 [ether] on eth1
? (10.0.2.3) at 52:54:00:12:35:03 [ether] on eth0
```

Again, as long are both supported and you can switch between them, this is just semantics. But if DHCP polling was deprecated without a viable alternative, it would be a show stopper for us.

**Comment by jlmcknight** [comment]
With `arpCacheEnabled` set to false I can't really test anything, because any api access fails, which includes initial boot into discovery because it hits http://rackhdserver:port/api/common/profiles and gets the nice big exception logged.  I just reset my vagrant environment and had to re-enable `arpCacheEnabled` in order to just get our tasks/graphs/skus installed properly, and then when I disable it again I can't do the initial pxeboot of a node even into discovery.

https://github.com/RackHD/on-core/pull/160 will need to go in before we can continue our testing efforts around this.

**Comment by jlongever** [comment]
@tldavies @benbp Is there any plan to reopen this PR https://github.com/RackHD/on-dhcp-proxy/pull/39 and add the config.json option so we can still support either MAC/IP lookup modes?  Once https://github.com/RackHD/on-core/pull/160 goes in it will still be inconvenient for a user to have to keep setting `serviceGraph` to true in the DHCP poller graph after updating builds;  the user maintains their own config.json settings.

**Comment by tldavies** [comment]
@jlongever Yes, the plan is to reopen open it with a config.json when RackHD/on-core#160 gets merged.

**Comment by jlongever** [comment]
@jlmcknight @ytjohn @tldavies PR https://github.com/RackHD/on-core/pull/160 has been merged.

**Comment by jlongever** [comment]
@jlmcknight did you remove `node_modules` from on-http and on-taskgraph and run `npm install` again to make sure on-core dependency was updated?

**Comment by ytjohn** [comment]
The debian packages themselves from bintray has the older lookup.js file.

```
2016-06-23 15:56:04 (13.9 MB/s) - ‘on-http_1.1-1master1_amd64.deb’ saved [49613584/49613584]

ytjohn@freshdesk:~/Downloads$ dpkg -c on-http_1.1-1master1_amd64.deb | grep lookup.js
-rw-r--r-- root/root       980 2016-06-06 09:08 ./var/renasar/on-http/lib/serializables/v1/lookup.js
-rw-r--r-- root/root      4756 2016-06-06 09:10 ./var/renasar/on-http/node_modules/on-tasks/node_modules/on-core/lib/models/lookup.js
-rw-r--r-- root/root     13431 2016-06-06 09:10 ./var/renasar/on-http/node_modules/on-tasks/node_modules/on-core/lib/services/lookup.js
-rw-r--r-- root/root      4756 2016-06-06 09:08 ./var/renasar/on-http/node_modules/on-core/lib/models/lookup.js
-rw-r--r-- root/root     13431 2016-06-06 09:08 ./var/renasar/on-http/node_modules/on-core/lib/services/lookup.js
```

To date, we haven't used npm to install anything.

**Comment by jlmcknight** [comment]
We are installing from the bintray debian packages, shouldn't need to run `npm install` for those should I?

**Comment by jlongever** [comment]
OK.  Looks like the bintray packages are not getting updated. 
```
travis_fold:end:dpl.1
[Bintray Upload] Reading descriptor file: .bintray.json
[Bintray Upload] Uploading file 'deb/on-http_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/on-http_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-api1.1_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-api1.1_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-api2.0_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-api2.0_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Uploading file 'deb/python-on-http-redfish-1.0_1.1-1master1_amd64.deb' to dists/trusty/main/binary-amd64/python-on-http-redfish-1.0_1.1-1master1_amd64.deb
[Bintray Upload] Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be deployed to.
[Bintray Upload] Publishing version 'master' of package 'packages'...
[Bintray Upload] Bintray response: 200 OK.
```

**Comment by amymullins** [comment]
FYI @anhou , not sure where your investigation of the bintray issues has left off...

**Comment by ytjohn** [comment]
I pulled some fresh copies from bintray and they have the current files. So the bintray issue is resolved. We'll test a recent copy and see how things work.

**Comment by ytjohn** [comment]
https://github.com/RackHD/on-dhcp-proxy/pull/50

**Comment by tldavies** [comment]
RackHD/on-dhcp-proxy#50 - This moves the dhcp-poller to on-dhcp-proxy

**Comment by tldavies** [comment]
RackHD/on-dhcp-proxy#50 - has been merged so the dhcp poller has been moved to be a config option
