### ISSUE TITLE
Graph.SKU.Discovery failing - mongo E11000 duplicate key error

### ISSUE THREAD

**Issue by hohene** [RackHD/RackHD#228]
Running on multiple stacks with latest RackHD version (master).
No nodes are being fully discovered.
Graph.Discovery and other task failing due to hitting duplicate TaskIDs in mongo.
Internal ODR 706 has full logs from the system.

```
snippet from the logs.
hohene@lab02:~/bugs$ more on-taskgraph.log
...
  - Graph.Switch.SKU.Discovery.Hooks.Post
  - Graph.RunUefi
  - Graph.BootstrapWinPE
  - Graph.Write.Quanta.BIOS.NVRAM
  - Graph.Arista.Zerotouch.vEOS
[info] [2016-05-13T03:35:32.942Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task runner started
 -> /lib/task-runner.js:435
TaskRunnerId: 946f8f0b-e3ee-4339-8cd0-f60195253343
domain:       default
[info] [2016-05-13T03:35:32.950Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduler started
 -> /lib/task-scheduler.js:676
schedulerId: 9885ddf4-4740-4b98-a372-c585b3c9eeda
domain:      default
[Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undefined:
 \u2022 graphId
   \u2022 A record with that `graphId` already exists (`1e4d58c2-13a2-4b8d-8a67-cdcc2a3d4f5f`).

Error (E_VALIDATION) :: 1 attribute is invalid
WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : \"1e4d58c2-13a2-4b8d-8a67-cdcc2
a3d4f5f\" }","op":{"taskId":"e21fa3f2-6b77-4db4-afb0-bdd0531cdbd0","graphId":"1e4d58c2-13a2-4b8d-8a67-cdcc2a3d4f5f","state":"pending","dependencies":{},"ter
minalOnStates":["succeeded","timeout","cancelled","failed"],"domain":"default","evaluated":false,"reachable":true,"taskRunnerLease":null,"taskRunnerHeartbea
t":null,"context":null,"createdAt":"2016-05-13T03:35:33.028Z","updatedAt":"2016-05-13T03:35:33.028Z","_id":"57354b85d7bf44244234c87b"}})
    at Function.MongoError.create (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/li
b/error.js:31:11)
    at toError (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:114:22)
    at /var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:597:23
    at handleCallback (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:96:12)
    at resultHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/bulk/ordered.js:419:14)
    at /var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.j
s:475:59
    at Callbacks.emit (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies
/server.js:95:3)
    at null.messageHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topol
ogies/server.js:249:23)
    at Socket.<anonymous> (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connec
tion/connection.js:300:20)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
Starting monorail taskgraph service
Starting monorail taskgraph service
[info] [2016-05-13T03:37:57.283Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (migrate => safe).
 -> /node_modules/on-core/lib/services/configuration.js:73
[info] [2016-05-13T03:37:57.380Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (color => undefined).
 -> /node_modules/on-core/lib/services/configuration.js:73
[info] [2016-05-13T03:37:57.381Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (logColorEnable => undefi
ned).
 -> /node_modules/on-core/lib/services/configuration.js:73
[info] [2016-05-13T03:37:57.748Z] [on-taskgraph] [TaskGraph.DataLoader] [Server] Loaded 74 tasks from Task.taskLibrary dependency
 -> /lib/loader.js:128
[info] [2016-05-13T03:37:57.748Z] [on-taskgraph] [TaskGraph.DataLoader] [Server] Loaded 62 graphs matching the pattern 'lib/graphs/**/*-graph.+(js|json)'
 -> /lib/loader.js:129
[info] [2016-05-13T03:37:57.801Z] [on-taskgraph] [TaskGraph.DataLoader] [Server] Loaded task/graph definitions: 
 -> /lib/loader.js:136
tasks: 
  - Task.Os.Esx.Analyze.Repo
  - Task.ArpPoller
  - Task.Os.Boot.LiveCD
  - Task.Linux.Bootstrap.Ubuntu
  - Task.WinPE.Bootstrap
  - Task.Catalog.ami
...
  - Graph.Write.Quanta.BIOS.NVRAM
  - Graph.Arista.Zerotouch.vEOS
[info] [2016-05-13T03:37:57.839Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task runner started
 -> /lib/task-runner.js:435
TaskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
domain:       default
[info] [2016-05-13T03:37:57.846Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduler started
 -> /lib/task-scheduler.js:676
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414
domain:      default
[info] [2016-05-13T03:37:57.892Z] [on-taskgraph] [TaskGraph] [Server] Task Graph Runner Started.
 -> /index.js:55
[debug] [2016-05-13T03:37:57.901Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     3bca965c-1662-4c90-9324-dde8aba18a21
taskId:      f0cc7ad0-d056-4651-99ce-5a15a5e52396
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414
[info] [2016-05-13T03:37:57.908Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task 
 -> /lib/task-runner.js:340
taskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
taskId:       f0cc7ad0-d056-4651-99ce-5a15a5e52396
taskName:     Task.ArpPoller
[info] [2016-05-13T03:37:57.942Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:339
taskId: f0cc7ad0-d056-4651-99ce-5a15a5e52396
name:   ARP poller
job:    Job.ArpPoller
[debug] [2016-05-13T03:37:57.943Z] [on-taskgraph] [Job.ArpPoller] [Server] Running job.
 -> /node_modules/on-tasks/lib/jobs/base-job.js:112
module:  Job.ArpPoller
name:    ArpPollerJob
options: 
  schedulerOverrides: 
    timeout: -1
taskId:  f0cc7ad0-d056-4651-99ce-5a15a5e52396
target:  none
[debug] [2016-05-13T03:37:58.315Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     1e4d58c2-13a2-4b8d-8a67-cdcc2a3d4f5f
taskId:      6f66f360-7495-47da-af01-044d1c1e746d
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414
[info] [2016-05-13T03:37:58.322Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task 
 -> /lib/task-runner.js:340
taskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
taskId:       6f66f360-7495-47da-af01-044d1c1e746d
taskName:     Task.Inline.Poller.WorkItems.Clean
[info] [2016-05-13T03:37:58.326Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:339
taskId: 6f66f360-7495-47da-af01-044d1c1e746d
name:   Clean Poller Work Items
job:    Job.WorkItems.Clean
[debug] [2016-05-13T03:37:58.327Z] [on-taskgraph] [Job.WorkItems.Clean] [Server] Running job.
 -> /node_modules/on-tasks/lib/jobs/base-job.js:112
module:  Job.WorkItems.Clean
name:    CleanWorkItemsJob
options: 
  schedulerOverrides: 
    timeout: -1
  queuePollInterval:  10000
  leaseAdjust:        0
taskId:  6f66f360-7495-47da-af01-044d1c1e746d
target:  none
[debug] [2016-05-13T03:37:58.948Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.18.1.209
  mac:   00:50:56:99:f2:41
  iface: eth0
  flag:  0x2
[debug] [2016-05-13T03:37:58.949Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.18.1.1
  mac:   00:50:56:99:ae:d3
  iface: eth0
  flag:  0x2
[debug] [2016-05-13T03:37:58.949Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.18.1.2
  mac:   00:00:00:00:00:00
  iface: eth0
  flag:  0x0
[debug] [2016-05-13T03:38:09.952Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    192.168.1.254
  mac:   00:0a:9c:53:ea:8e
  iface: eth2
  flag:  0x2
[debug] [2016-05-13T03:38:48.972Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.2
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:38:50.974Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.2
  mac:   00:1e:67:94:5d:3f
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:38:54.582Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     688d814b-2e95-4103-b80e-d36a925640fe
taskId:      5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414
[info] [2016-05-13T03:38:54.593Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task 
 -> /lib/task-runner.js:340
taskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
taskId:       5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
taskName:     Task.Snmp.Ping
[info] [2016-05-13T03:38:54.605Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:339
taskId: 5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
name:   Ping Snmp
job:    Job.Snmp.Collect
[debug] [2016-05-13T03:38:54.618Z] [on-taskgraph] [Job.Snmp.Collect] [4856de] Running job.
 -> /node_modules/on-tasks/lib/jobs/base-job.js:112
module:  Job.Snmp.Collect
name:    SnmpCollectionJob
options: 
  oids: 
    - SNMPv2-MIB::sysDescr
taskId:  5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
target:  57354c4e6ecb6d2f084856de
[info] [2016-05-13T03:38:54.702Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
 -> /lib/task-runner.js:296
instanceId:   5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
state:        succeeded
taskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
[debug] [2016-05-13T03:38:54.706Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Listener received task finished event, triggering evaluation
 -> /lib/task-scheduler.js:525
data: 
  taskId:           5f110bc9-4b4c-4d78-bbfc-43d3fc488a1b
  graphId:          688d814b-2e95-4103-b80e-d36a925640fe
  state:            succeeded
  context: 
    target:  57354c4e6ecb6d2f084856de
    graphId: 688d814b-2e95-4103-b80e-d36a925640fe
  terminalOnStates: 
    - timeout
    - cancelled
    - failed
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414
[debug] [2016-05-13T03:38:54.976Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.18.1.123
  mac:   00:1c:73:62:3a:e6
  iface: eth0
  flag:  0x2
[debug] [2016-05-13T03:39:02.980Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.3
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:39:03.983Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.6
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:39:03.984Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.4
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:39:03.984Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.5
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:39:04.979Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.3
  mac:   2c:60:0c:7a:7e:c2
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:39:05.979Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.6
  mac:   2c:60:0c:6e:a5:9a
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:39:05.979Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.4
  mac:   2c:60:0c:7a:7f:e0
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:39:05.980Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.5
  mac:   2c:60:0c:7a:7f:17
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:39:21.985Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.7
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:39:23.986Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.7
  mac:   2c:60:0c:ad:d4:42
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:42:30.063Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.8
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:42:30.064Z] [on-taskgraph] [Job.ArpPoller] [Server] Remove Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:99
entry: 
  ip:    172.31.128.9
  mac:   00:00:00:00:00:00
  iface: eth1
  flag:  0x0
[debug] [2016-05-13T03:42:34.063Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.8
  mac:   2c:60:0c:ad:d4:40
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:42:34.064Z] [on-taskgraph] [Job.ArpPoller] [Server] Add/Update Lookup
 -> /node_modules/on-tasks/lib/jobs/arp-poller.js:103
entry: 
  ip:    172.31.128.9
  mac:   2c:60:0c:6f:b8:35
  iface: eth1
  flag:  0x2
[debug] [2016-05-13T03:42:34.180Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     fa5d8d34-1c34-4e67-b4b1-953a9f61fb9a
taskId:      b2694644-f435-43f9-84b0-dbdeae48b1ad
schedulerId: bb42d838-218a-42f4-8b19-cbd58ff7a414


[info] [2016-05-13T03:42:34.189Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task 
 -> /lib/task-runner.js:340
taskRunnerId: c492a3ee-067a-490a-b0bd-55b76eaca8dd
taskId:       b2694644-f435-43f9-84b0-dbdeae48b1ad
taskName:     Task.Graph.Run.Discovery

[info] [2016-05-13T03:42:34.194Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:339
taskId: b2694644-f435-43f9-84b0-dbdeae48b1ad
name:   Run Discovery Graph
job:    Job.Graph.Run

[debug] [2016-05-13T03:42:34.195Z] [on-taskgraph] [Job.Graph.Run] [Server] Running job.
 -> /node_modules/on-tasks/lib/jobs/base-job.js:112
module:  Job.Graph.Run
name:    RunGraphJob
options: 
  graphName:    Graph.Discovery
  graphOptions: 
    target:     57354d296ecb6d2f084856e4
    instanceId: 7abee098-87ad-40fa-8f6f-4eb408f0271f
  instanceId:   7abee098-87ad-40fa-8f6f-4eb408f0271f
taskId:  b2694644-f435-43f9-84b0-dbdeae48b1ad
target:  none
[error] [2016-05-13T03:42:34.267Z] [on-taskgraph] [Job.Graph.Run] [Server] Error starting graph for task.
 -> /node_modules/on-tasks/lib/jobs/run-graph.js:84
taskId:    b2694644-f435-43f9-84b0-dbdeae48b1ad
graphName: Graph.Discovery
error: 
  code:              E_VALIDATION
  invalidAttributes: 
    graphId: 
      - 
        rule:    unique
        value:   7abee098-87ad-40fa-8f6f-4eb408f0271f
        message: A record with that `graphId` already exists (`7abee098-87ad-40fa-8f6f-4eb408f0271f`).
  originalError: 
    name:         MongoError
    message:      E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : "7abee098-87ad-40fa-8f6f-4eb408f0271f" }
    driver:       true
    code:         11000
    index:        0
    errmsg:       E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : "7abee098-87ad-40fa-8f6f-4eb408f0271f" }
    getOperation: 

    toJSON: 

    toString: 

  _e: 
    name:         MongoError
    message:      E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : "7abee098-87ad-40fa-8f6f-4eb408f0271f" }
    driver:       true
    code:         11000
    index:        0
    errmsg:       E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : "7abee098-87ad-40fa-8f6f-4eb408f0271f" }
    getOperation: 

    toJSON: 

    toString: 

  rawStack: 
    """
      WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error index: pxe.taskdependencies.$graphId_1  dup key: { : \"7abee098-87ad-40fa-8f6f
-4eb408f0271f\" }","op":{"taskId":"a686cbfd-50c4-4eaf-a429-ae7c1c84a1c8","graphId":"7abee098-87ad-40fa-8f6f-4eb408f0271f","state":"pending","dependencies":{
"56df5c32-400b-4a24-ad68-b6a8943fe8fb":"finished"},"terminalOnStates":[],"domain":"default","evaluated":false,"reachable":true,"taskRunnerLease":null,"taskR
unnerHeartbeat":null,"context":null,"createdAt":"2016-05-13T03:42:34.247Z","updatedAt":"2016-05-13T03:42:34.247Z","_id":"57354d2a5b4fcd2c088da27d"}})
          at Function.MongoError.create (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-c
ore/lib/error.js:31:11)
          at toError (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:114:22)
          at /var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:597:23
          at handleCallback (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:96:12)
          at resultHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/lib/bulk/ordered.js:419:14)
          at /var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_sup
port.js:475:59
          at Callbacks.emit (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topo
logies/server.js:95:3)
          at null.messageHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib
/topologies/server.js:249:23)
          at Socket.<anonymous> (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/
connection/connection.js:300:20)
          at Socket.EventEmitter.emit (events.js:95:17)
          at Socket.<anonymous> (_stream_readable.js:746:14)
          at Socket.EventEmitter.emit (events.js:92:17)
          at emitReadable_ (_stream_readable.js:408:10)
          at emitReadable (_stream_readable.js:404:5)
          at readableAddChunk (_stream_readable.js:165:9)
          at Socket.Readable.push (_stream_readable.js:127:10)
          at TCP.onread (net.js:526:21)
    """
  details: 
    """
      Invalid attributes sent to undefined:
       \u2022 graphId
         \u2022 A record with that `graphId` already exists (`7abee098-87ad-40fa-8f6f-4eb408f0271f`).
      
    """
  reason:            1 attribute is invalid
  status:            400
[error] [2016-05-13T03:42:34.279Z] [on-taskgraph] [Task.Task] [Server] Task failed
```

**Comment by benbp** [comment]
@VulpesArtificem
