### ISSUE TITLE
Get lookup always returns "SchemaError: JSON Schema Violation"

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#230]
The API "GET /api/1.1/lookups" will always return the JSON schema violation error using the latest master branch code.

The error detail:
```
17:28:47 graph.1  |  name: Pollers.IPMI
17:52:03 http.1   |  [error] [2016-05-16T09:52:03.293Z] [on-http] [Http.Services.RestApi] [Server] SchemaError: JSON Schema Violation
17:52:03 http.1   |   -> /lib/services/rest-api-service.js:323
17:52:03 http.1   |  error:
17:52:03 http.1   |    stack:
17:52:03 http.1   |      - Error: SchemaError: JSON Schema Violation
17:52:03 http.1   |      -     at Lookup.ValidatableFactory.Validatable.validate (/home/yuanf/src/on-core/lib/common/validatable.js:50:25)
17:52:03 http.1   |      -     at Lookup.ValidatableFactory.Validatable.validateAsModel (/home/yuanf/src/on-core/lib/common/validatable.js:65:21)
17:52:03 http.1   |      -     at /home/yuanf/src/on-http/lib/services/rest-api-service.js:403:35
17:52:03 http.1   |      -     at tryCatcher (/home/yuanf/src/on-core/node_modules/bluebird/js/main/util.js:26:23)
17:52:03 http.1   |      -     at Promise._settlePromiseFromHandler (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:507:31)
17:52:03 http.1   |      -     at Promise._settlePromiseAt (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:581:18)
17:52:03 http.1   |      -     at Promise._settlePromises (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:697:14)
17:52:03 http.1   |      -     at Async._drainQueue (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:123:16)
17:52:03 http.1   |      -     at Async._drainQueues (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:133:10)
17:52:03 http.1   |      -     at Async.drainQueues (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:15:14)
17:52:03 http.1   |      -     at process._tickDomainCallback (node.js:502:13)
17:52:03 http.1   |    message:       SchemaError: JSON Schema Violation
17:52:03 http.1   |    violations:
17:52:03 http.1   |      -
17:52:03 http.1   |        property: instance.ipAddress
17:52:03 http.1   |        message:  is not of a type(s) string
17:52:03 http.1   |        schema:
17:52:03 http.1   |          type:   string
17:52:03 http.1   |          format: ipv4
17:52:03 http.1   |        name:     type
17:52:03 http.1   |        argument:
17:52:03 http.1   |          - string
17:52:03 http.1   |        stack:    instance.ipAddress is not of a type(s) string
17:52:03 http.1   |    isOperational: true
17:52:03 http.1   |  path:  /lookups
17:52:03 http.1   |  [debug] [2016-05-16T09:52:03.294Z] [on-http] [Http.Server] [Server] http: GET 500 30.770 - /api/common/lookups?q=
17:52:03 http.1   |   -> /lib/services/http-service.js:326
17:52:03 http.1   |  ipAddress: 127.0.0.1
17:52:03 http.1   |  Using monkey-patched Error.prototype.toJSON method, which will be deprecated soon.
17:52:03 http.1   |  Error: SchemaError: JSON Schema Violation
17:52:03 http.1   |      at Lookup.ValidatableFactory.Validatable.validate (/home/yuanf/src/on-core/lib/common/validatable.js:50:25)
17:52:03 http.1   |      at Lookup.ValidatableFactory.Validatable.validateAsModel (/home/yuanf/src/on-core/lib/common/validatable.js:65:21)
17:52:03 http.1   |      at /home/yuanf/src/on-http/lib/services/rest-api-service.js:403:35
17:52:03 http.1   |      at tryCatcher (/home/yuanf/src/on-core/node_modules/bluebird/js/main/util.js:26:23)
17:52:03 http.1   |      at Promise._settlePromiseFromHandler (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:507:31)
17:52:03 http.1   |      at Promise._settlePromiseAt (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:581:18)
17:52:03 http.1   |      at Promise._settlePromises (/home/yuanf/src/on-core/node_modules/bluebird/js/main/promise.js:697:14)
17:52:03 http.1   |      at Async._drainQueue (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:123:16)
17:52:03 http.1   |      at Async._drainQueues (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:133:10)
17:52:03 http.1   |      at Async.drainQueues (/home/yuanf/src/on-core/node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by yyscamper** [comment]
@jlongever , it there some relationship with your recent arp poller?

**Comment by jlongever** [comment]
Yes, you need this fix: https://github.com/RackHD/on-tasks/pull/206

**Comment by heckj** [comment]
@yyscamper is this resolved with the PR that Joel referenced?

**Comment by benbp** [comment]
Going to close for now as it seems resolved.. Re-open if it's not.
