### ISSUE TITLE
Rebooting the ORA in the middle of a node discovery leave the node stuck- ODR 736

### ISSUE THREAD

**Issue by manfrednde** [RackHD/RackHD#243]
Rebooting the ORA in the middle of a node discovery will leave the node stuck. 
When the ORA will come back online the discovery graph will be in pending state however the sku discovery will be in a failed state. When I reboot the compute node, it pxe boot again and the discovery graph complete but the sku discovery graph is still in a failed state and the node stays not even in a partially discovered state.

**Comment by manfrednde** [comment]
Related to ODR 736

**Comment by heckj** [comment]
@manfrednde can you couch this in terms of what it means for RackHD? ORA isn't something relevant to the technology stack.

I think what you're trying to say is the process where graphs are running graphs has an error across failure of the process that isn't resuming properly, but there's really no detail in what you're including here to debug it, and anything ODR related is opaque the community since that's an internal EMC bug tracking system.

If you're going to open a bug in the RackHD system, please provide sufficient detail and make it relevant to RackHD.

**Comment by manfrednde** [comment]
@heckj  Thank you for the advise I will provide more details and relevant screenshots.

**Comment by benbp** [comment]
@manfrednde any updates here? Have you continued to see this issue?

**Comment by patelb10** [comment]
Step to reproduce issue.
1) Reboot OVA in middle of Node Discovery.
snippet from stack:
onrack@stack14-ora:/var/log/upstart$  curl http://localhost:8080/api/common/workflows/7c3c3e5c-58ba-43fd-8f33-61054cd1c946 | python -mjson.tool | grep -e injectable -e state -e error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6631  100  6631    0     0   124k      0 --:--:-- --:--:-- --:--:--  124k
        "injectableName": "Graph.SKU.Discovery",
                    "injectableName": "Task.Graph.Run.Discovery",
                    "injectableName": "Task.Inline.Pollers.CreateDefault",
                    "injectableName": "Task.Graph.Run.SkuSpecific",
    "injectableName": "Graph.SKU.Discovery",
            "injectableName": "Task.Catalog.GenerateSku",
            "state": "failed",
            "injectableName": "Task.Catalog.GenerateTag",
            "state": "failed",
            "error": "Error: Unable to run multiple task graphs against a single target.\n    at Promise.resolve.then.then.then.TaskGraph.create.definition (/var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/workflow-tool.js:55:27)\n    at tryCatcher (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickDomainCallback (node.js:459:13)",
            "injectableName": "Task.Graph.Run.Discovery",
            "state": "failed",
            "injectableName": "Task.Graph.Run.SkuSpecific",
            "state": "failed",
            "injectableName": "Task.Catalog.GenerateEnclosure",
            "state": "failed",
            "injectableName": "Task.Inline.Pollers.CreateDefault",
            "state": "failed",

onrack@stack14-ora:/var/log/upstart$  curl http://localhost:8080/api/common/workflows/151a97db-ef68-4a9a-b5cd-2f5a2f0291b2 | python -mjson.tool | grep -e injectable -e state -e error
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100 11718  100 11718    0     0   558k      0 --:--:-- --:--:-- --:--:--  572k
       "injectableName": "Graph.Discovery",
   "injectableName": "Graph.Discovery",
           "injectableName": "Task.Catalog.ohai",
           "state": "pending",
           "injectableName": "Task.ProcShellReboot",
           "state": "pending",
           "injectableName": "Task.Catalog.smart",
           "state": "pending",
           "injectableName": "Task.Catalog.bmc",
           "state": "pending",
           "injectableName": "Task.Catalog.Drive.Id",
           "state": "pending",
           "injectableName": "Task.Catalog.LLDP",
           "state": "pending",
           "injectableName": "Task.Catalog.lsall",
           "state": "pending",
           "injectableName": "Task.Trigger.Send.Finish",
           "state": "pending",
           "injectableName": "Task.Catalog.dmi",
           "state": "pending",
           "injectableName": "Task.Linux.Bootstrap.Ubuntu",
           "state": "pending",
           "injectableName": "Task.Catalog.megaraid",
           "state": "pending",

2) Reboot Node again to get discover.

onrack@stack14-ora:/var/log/upstart$  curl http://localhost:8080/api/common/workflows/151a97db-ef68-4a9a-b5cd-2f5a2f0291b2 | python -mjson.tool | grep -e injectable -e state -e error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12691  100 12691    0     0   909k      0 --:--:-- --:--:-- --:--:--  953k
        "injectableName": "Graph.Discovery",
    "injectableName": "Graph.Discovery",
            "injectableName": "Task.Catalog.ohai",
            "state": "succeeded",
            "injectableName": "Task.ProcShellReboot",
            "state": "succeeded",
            "injectableName": "Task.Catalog.smart",
            "state": "succeeded",
            "injectableName": "Task.Catalog.bmc",
            "state": "succeeded",
            "injectableName": "Task.Catalog.Drive.Id",
            "state": "succeeded",
            "injectableName": "Task.Catalog.LLDP",
            "state": "succeeded",
            "injectableName": "Task.Catalog.lsall",
            "state": "succeeded",
            "injectableName": "Task.Trigger.Send.Finish",
            "state": "succeeded",
            "injectableName": "Task.Catalog.dmi",
            "state": "succeeded",
            "injectableName": "Task.Linux.Bootstrap.Ubuntu",
            "state": "succeeded",
            "error": "Error: Encountered a failure running remote commands\n    at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/command-util.js:82:23\n    at tryCatcher (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/util.js:26:23)\n    at MappingPromiseArray._promiseFulfilled (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/map.js:56:38)\n    at MappingPromiseArray.init [as _init$] (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/promise_array.js:92:18)\n    at MappingPromiseArray.init (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/map.js:29:23)\n    at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickDomainCallback (node.js:459:13)",
            "injectableName": "Task.Catalog.megaraid",
            "state": "failed",

onrack@stack14-ora:/var/log/upstart$  curl http://localhost:8080/api/common/workflows/7c3c3e5c-58ba-43fd-8f33-61054cd1c946 | python -mjson.tool | grep -e injectable -e state -e error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6631  100  6631    0     0   272k      0 --:--:-- --:--:-- --:--:--  281k
        "injectableName": "Graph.SKU.Discovery",
                    "injectableName": "Task.Graph.Run.Discovery",
                    "injectableName": "Task.Inline.Pollers.CreateDefault",
                    "injectableName": "Task.Graph.Run.SkuSpecific",
    "injectableName": "Graph.SKU.Discovery",
            "injectableName": "Task.Catalog.GenerateSku",
            "state": "failed",
            "injectableName": "Task.Catalog.GenerateTag",
            "state": "failed",
            "error": "Error: Unable to run multiple task graphs against a single target.\n    at Promise.resolve.then.then.then.TaskGraph.create.definition (/var/renasar/on-taskgraph/node_modules/on-tasks/lib/utils/job-utils/workflow-tool.js:55:27)\n    at tryCatcher (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:133:10)\n    at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/bluebird/js/main/async.js:15:14)\n    at process._tickDomainCallback (node.js:459:13)",
            "injectableName": "Task.Graph.Run.Discovery",
            "state": "failed",
            "injectableName": "Task.Graph.Run.SkuSpecific",
            "state": "failed",
            "injectableName": "Task.Catalog.GenerateEnclosure",
            "state": "failed",
            "injectableName": "Task.Inline.Pollers.CreateDefault",
            "state": "failed",

Logs file is
https://web.hwimo.lab.emc.com/qa/log/bug_logs/243/

**Comment by benbp** [comment]
My bet is that this is caused by https://github.com/RackHD/RackHD/issues/277

**Comment by pscharla** [comment]
@manfrednde Fixes for this now merged into RackHD master. Please verify.
