### ISSUE TITLE
Test failure building on-taskgraph:  Graph Library.should validate all existing graphs not requiring user input for null values

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#246]
Error Message

required option obmServiceName for task Task.Obm.Node.PxeBoot in graph Graph.BootLiveCD
Stacktrace

AssertionError: required option obmServiceName for task Task.Obm.Node.PxeBoot in graph Graph.BootLiveCD
    at AssertService.(anonymous function) [as ok] (node_modules/on-core/lib/common/assert.js:30:28)
    at node_modules/on-core/lib/workflow/task-graph.js:336:20
    at arrayEach (node_modules/lodash/index.js:1289:13)
    at Function.&lt;anonymous&gt; (node_modules/lodash/index.js:3345:13)
    at TaskGraph._validateOptions (node_modules/on-core/lib/workflow/task-graph.js:328:11)
    at node_modules/on-core/lib/workflow/task-graph.js:274:26
    at arrayEach (node_modules/lodash/index.js:1289:13)
    at Function.&lt;anonymous&gt; (node_modules/lodash/index.js:3345:13)
    at node_modules/on-core/lib/workflow/task-graph.js:271:19
    at tryCatcher (node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)

**Comment by johren** [comment]
Failure appears to have started when one of these two PRs came in:
https://github.com/RackHD/on-tasks/pull/205
https://github.com/RackHD/on-tasks/pull/219

Those are the three commits that came in on the first Jenkins build that hit this failure.

**Comment by heckj** [comment]
@johren was this resolved over the weekend, or is this still pending?

**Comment by johren** [comment]
Still pending

**Comment by heckj** [comment]
@DavidjohnBlodgett @benbp I'm presuming the removal of default IPMI OBM service expectation is what's causing some of this, does that read accurately to you? Do we just need to add a default OBM service to the `Graph.BootLiveCD` to resolve this?

**Comment by johren** [comment]
Correction, I got my issues confused.  This does appear to have resolved late on Friday.

**Comment by heckj** [comment]
@johren can you give me the detail of how you're invoking this graph `Graph.BootLiveCD` and if the node associated with it has an OBM service already defined?

**Comment by heckj** [comment]
Oh - okay, closing then
