### ISSUE TITLE
Current master Docker image for on-taskgraph fails

### ISSUE THREAD

**Issue by codenrhoden** [RackHD/RackHD#258]
When starting from a clean enviroment and following the instructions at https://github.com/RackHD/RackHD/blob/master/docker/README.md for OS X, the `on-taskgraph` container fails to start up.  Looking at its logs, I see:

```
docker@boot2docker:~$ docker logs docker_taskgraph_1
Error creating initial AMQP transmit connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP receive connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP transmit connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP receive connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP transmit connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP receive connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP transmit connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
Error creating initial AMQP receive connection (amqp://127.0.0.1), retrying... connect ECONNREFUSED 127.0.0.1:5672
[info] [2016-06-06T21:28:16.085Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (migrate => safe).
 -> /RackHD/on-core/lib/services/configuration.js:73
[info] [2016-06-06T21:28:16.219Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (color => undefined).
 -> /RackHD/on-core/lib/services/configuration.js:73
[info] [2016-06-06T21:28:16.220Z] [on-taskgraph] [Services.Configuration] [Server] Configuration value is undefined, using default (logColorEnable => undefined).
 -> /RackHD/on-core/lib/services/configuration.js:73
The dollar ($) prefixed field '$taskTimeout' in 'options.firstboot-callback-uri-wait.$taskTimeout' is not valid for storage.
MongoError: The dollar ($) prefixed field '$taskTimeout' in 'options.firstboot-callback-uri-wait.$taskTimeout' is not valid for storage.
    at Function.MongoError.create (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:778:66
    at Callbacks.emit (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/RackHD/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:300:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```

Looking in RackHD/on-taskgraph, I can the line in question here: https://github.com/RackHD/on-taskgraph/blob/master/lib/graphs/install-esx-graph.js#L22, which came in with https://github.com/RackHD/on-taskgraph/commit/14e930721db0f7a785f4218276dfc9b48c80342f

I don't really get why it says this is invalid for storage -- I don't see the storage aspect of it.

**Comment by codenrhoden** [comment]
One note of interest. I actually updated the boot2docker vbox image to `1.11.1` before launching all this -- I already have a 1.11 client on my machine, so if I don't do that first I get incompatible APIs.

**Comment by michaelsteven** [comment]
I'm seeing this problem/exact same error when trying to run RackHD on a CentOS VM that uses Docker version 1.10.2.  Subscribing to this bug.

**Comment by rolandpoulter** [comment]
https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names
