### ISSUE TITLE
The skip condition of Testing Graph.Discovery  is not  rigorous enough

### ISSUE THREAD

**Issue by changev** [RackHD/RackHD#270]
Now when found data **not null** in 
```
/api/1.1/nodes
```
the Testing Graph.Discovery will be **skipped**. 

But Graph.Discovery **not only** writes the nodes' data in mongo but also does other jobs like collecting catalogs, so finding data in **/api/1.1/nodes** doesn't mean  Graph.Discovery is over.
Another side ,if **not skipped**, the Graph.Discovery will monitor amqp info and **make sure** Graph.Discovery be finished.
So the judging conditions of the two flows are not symmetrical.

Then in some cases, after rackhd service is running  and all the nodes are power on for test ,but  there are **too many** nodes so the power on spends more time hence before Test Graph.Discovery some nodes has been **imperfect** discovered(/api/1.1/nodes not null but catalogs null), as a result  Test Graph.Discovery will be skipped and next test cases will fail.

So i recommand enhancement of the skip condition in Testing Graph.Discovery.

**Comment by benbp** [comment]
I'm a little confused as to the problem description here. Currently the criteria used for whether a node should be discovered is whether it has catalogs or not (see https://github.com/RackHD/on-core/blob/master/lib/models/node.js#L74-L83) and whether there is already an active workflow for it (https://github.com/RackHD/on-http/blob/88b7f5981cd37f67717ff77b97cd6dd3690a205b/lib/services/profiles-api-service.js#L107-L116).

Are you referring solely to RackHD here, or also to OnRack, or perhaps to the RackHD integration test suite, or something else? I don't believe there are any places within the RackHD code that make API calls to `/api/1.1/nodes` in order to determine behavior, but there probably are within OnRack and our integration tests. Which Graph.Discovery test case are you specifically referring to?

**Comment by changev** [comment]
Thanks for your attention. 
It's my fault that I didn't tell this is Graph.Discovery in **proboscis function test**(see https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/nodes_tests.py#L113-115).
and the ```check_compute_count``` just use ```Nodes().nodes_get()``` which get data from ```/api/1.1/nodes```.

**Comment by benbp** [comment]
Ah, ok that makes sense @changev thanks. Yep it seems like we could be doing that better with a catalog check.

**Comment by changev** [comment]
@benbp thanks.

It's a good way to add catalog checking in "already discovered" criteria, but depends on our testing experience maybe it's imperfect too.
We add physical nodes in our testing and its 'discovery' is far slowly than vnode. So sometimes even the discovery of vnode is finished , we still can't find all the physical nodes in ```/api/1.1/nodes```.
So the next cases will fail too.
I solved this problem with a env vars 'NODES_NUMBER' which indicates how many nodes we have to test, and few lines of codes were changed.
So if there are any other  ways to solve this problem？
Thanks!

**Comment by jlongever** [comment]
@changev @benbp The test doesn't rely on a GET /nodes to determine if the node was discovered,  it relies on the number of node documents created to determine how many completed discovery graphs to wait for.

For each completed discovery graph a count is incremented and compared: 
https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/nodes_tests.py#L142
https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/nodes_tests.py#L145

You can certainly add a catalog check per completed discovery graph,  but it won't solve the issue where some systems take longer to discover.  The actual timing condition is how long it takes for a system to make a PXE request and have RackHD create a new node document to be included in the total node count.

**Comment by changev** [comment]
@jlongever For now vnods are hard-coded in test.sh, In order to facilitate extension they could be config in smoke-test parameters, so a vnodes number could be provided to test cases(perhaps according to env var), 
```
if self.check_compute_count() == os.environ['VNODES_NUMBER']:
            LOG.warning('Nodes already discovered!')
            return
```
and
```
check = os.environ['VNODES_NUMBER']
```

A little ugly, but workable

**Comment by jlongever** [comment]
@changev As I mentioned above,  the node count is determined by the number of node documents created by RackHD per initial PXE profile request (it's a dynamic count, not fixed).   Adding a fixed node count probably won't solve the real problem,  which is, why is the test missing  `graph.finished` AMQP messages for some nodes.

The issue is obvious inline:

```
20:45:21 2016-09-11 20:45:21,579:tests.api.v1_1.nodes_tests:INFO - Graph.SKU.Discovery - target: 57d5fa559d0e7175086eef87, status: succeeded, route: b20a0dbf-40d0-4099-80f6-94d4597300ad, duration: 0:01:24.463419
20:45:31 2016-09-11 20:45:31,076:tests.api.v1_1.nodes_tests:INFO - Graph.SKU.Discovery - target: 57d5fa5f9d0e7175086eef95, status: succeeded, route: 8709facd-98b4-4d85-8414-86f32a9b838e, duration: 0:01:33.959987
**21:03:57 2016-09-11 21:03:57,176:modules.worker:ERROR - subtask timeout after 1200 seconds, (id=discovery), stopping..**
21:03:57 2016-09-11 21:03:57,177:kombu:INFO - Stopping AMQP worker <unbound Queue graph.finished -> <unbound Exchange on.events(topic)> -> graph.finished.*>
```

And reported at the end:
```
======================================================================
21:04:34 FAIL: Testing Graph.Discovery completion
21:04:34 ----------------------------------------------------------------------
21:04:34 Traceback (most recent call last):
21:04:34   File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
21:04:34     compatability.capture_type_error(s_func)
21:04:34   File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
21:04:34     func()
21:04:34   File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
21:04:34     func(test_case.state.get_state())
21:04:34   File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v1_1/nodes_tests.py", line 122, in test_nodes_discovery
21:04:34     message='timeout waiting for task {0}'.format(self.__task.id))
21:04:34 AssertionError: timeout waiting for task discovery
21:04:34 -------------------- >> begin captured logging << --------------------
```

This is telling us that the handler thread running to process each AMQP `graph.finished` never got the last event message and timed out after 20 minutes.  It did however, process 2 of the 3 nodes events.

**Comment by jlongever** [comment]
@changev With ^^ that said.   I think an update to the handler code in the node discovery test should be updated to include any potential failure that occurred during the discovery workflow.   Currently it only checks to see if the workflow succeeded:
https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/nodes_tests.py#L136

But it should also be checking for a failure similar to the workflow tests:
https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/workflows_tests.py#L220

That way it would be easier to determine what the cause of the failure was (if any);  otherwise we're stuff usually parsing the `vagrant.log` file:
http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-Functional/9842/artifact/build/vagrant.log

**Comment by changev** [comment]
@jlongever I thinks that;s two things.
1. Testing Graph.Discovery timed out after 20 minutes
2. Testing Graph.Discovery just skip when ```curl localhost:port/api/2.0/nodes``` not empty, and with incomplete catalogs next cases will fail.

About 1st problem, we've tracked it for a long time and find several possible reason:
* Process Exited Abnormally without error in context, on-taskgraph and on-http process both have such thing happened. We consider this may be a foreman issue and I'm planning to compare the stability Foreman and PM2, intend to replace Foreman if necessary.
* When vagrant up of after up for a while, mongo or rabbitmq service failed to start or stop abnormally.
We still can't find the root cause for this issue.

The 2nd problem is what I put forward here, and now I just have a workaround. And I fully expect your advice. Thanks.

**Comment by jlongever** [comment]
@changev 

For # 1, I'm not convinced that is the main reason since some nodes get discovered (this vagrant.log shows all 3 nodes booting, however the 3rd failed discovery (http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-Functional/9842/artifact/build/vagrant.log).   But if you think there is a foreman issue,  then that should probably be addressed.

For # 2,  that is expected behavior because the 1.1 API discovery tests had already run and discovered nodes.  You would have to delete all nodes prior to running 2.0 API discovery tests, otherwise it assumes nodes exists and continues.

Keep in mind the nodes discovery tests have a history running consistently unless a code regression gets introduced to master.

Any way,  I put up a PR to log the full workflow task data on graph failure (discovery timeout) and only ACK the AMQP message if graph/route IDs match: https://github.com/RackHD/RackHD/pull/416

**Comment by changev** [comment]
@jlongever This issue is just about api1.1, **sometimes** after nodeOn, before run discovery test, nodes info could be found in mongo but catalogs are still been collecting.

At this time if skip test discovery not waiting for discovery finished, next cases will fail.

**Comment by amymullins** [comment]
@changev and @jlongever if this is just an api 1.1 issue, should we make this a very low priority issue as we are currently in discussions for 1.1 API deprecation?  And once deprecated, the 1.1 based tests are also expected to be deprecated.

**Comment by changev** [comment]
@amymullins It's a api 1.1 test case issue but if 1.1 deprecated, api 2.0 tests will suffer this issue too.

Maybe I should explain more:
     Actually this is a node discovery test case issue. Now 1.1 tests run and then 2.0 tests run, so in 2.0 tests discovery is skipped. If 1.1 tests deprecated, 2.0 tests will test discovery too, and face the same issue.

This is indeed a low priority issue because it is not normally repeatable.

**Comment by amymullins** [comment]
Got it @changev , thanks for the clarification!    If we do see it again, hopefully we'll catch more details on the error with the PR @jlongever mentions above (#416)
