### ISSUE TITLE
GenerateEnclosure doesn't tolerate a dash("-") in serial number

### ISSUE THREAD

**Issue by jlmcknight** [RackHD/RackHD#282]
I am currently working with some new hardware in our lab.  These are Atos BULL servers that have large memory footprints for SAP workloads.

After discovery runs, the job that kicks off to generate the enclosure fails with the following error:

```
  03cca1d8-bba1-499d-b4a1-f7788e84f5c8:
    error:
      """

        AggregateError of:
            Error: No valid serial number in SN: XAN-S18-01998
            Error: No valid serial number in SN: XAN-S18-01998

            at SomePromiseArray._promiseRejected (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/some.js:67:17)
            at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:589:26)
            at Promise._settlePromises (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
            at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
            at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
            at Async.drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
            at process._tickDomainCallback (node.js:459:13)
      """
    friendlyName:     Generate Enclosure
    ignoreFailure:    true
    implementsTask:   Task.Base.Catalog.GenerateEnclosure
    injectableName:   Task.Catalog.GenerateEnclosure
    instanceId:       03cca1d8-bba1-499d-b4a1-f7788e84f5c8
    name:             Task.Catalog.GenerateEnclosure
    options:
      nodeId: 576c38e1af94799c6a36e238
    properties:

    runJob:           Job.Catalog.GenerateEnclosure
    state:            failed
```

These systems do indeed have a dash ("-") in their serial number.  Looking at `generate-enclosure.js`, I see a regex of the form:

`[^[\w]+$]`

This regex matches word characters `[a-zA-Z0-9_]` so the failure is because there is a dash in the serial number.

We will need to have `generate-enclsoure.js` updated to handle nodes that have a dash in the serial number.

I can provide more data if you need it to help with this, just let me know.

**Comment by jlmcknight** [comment]
The file/line with the regex in question:

https://github.com/RackHD/on-tasks/blob/0bdeda8103ba32912ed83a3b1e36fad4eac19586/lib/jobs/generate-enclosure.js#L176

**Comment by benbp** [comment]
FYI @iceiilin

**Comment by leoyjchang** [comment]
Story has been created in Maglev backlog to resolve this issue. at https://www.pivotaltracker.com/story/show/123272271

**Comment by iceiilin** [comment]
Fixed by modifying regex when determining serial number
