### ISSUE TITLE
Traceback in taskgraph - Task Cancellation Error

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#313]
@cygnus8595 reported in slack today that he was seeing timeout and failures with his discovery process. While scanning the snippet (included below), it looks like there's an error being reported related to cancellation subscriptions in the workflow engine: `TypeError: Cannot read property 'subscribe' of undefined`

The log detail:

```
12:01:27 PM syslog.1 |  [info] [2016-07-12T18:01:27.488Z] [on-syslog] [Syslog] [e0040e] ipxe: Starting CentOS/RHEL 6.5 installer for
12:01:27 PM syslog.1 |   -> /lib/app.js:65
12:01:27 PM syslog.1 |  facility: 0
12:01:27 PM syslog.1 |  priority: 6
12:01:27 PM syslog.1 |  [info] [2016-07-12T18:01:27.556Z] [on-syslog] [Syslog] [e0040e] ipxe: http://10.84.194.98:9080/centos/6/os/x86_64/images/pxeboot/vmlinuz... ok
12:01:27 PM syslog.1 |   -> /lib/app.js:65
12:01:27 PM syslog.1 |  facility: 0
12:01:27 PM syslog.1 |  priority: 6
12:01:27 PM syslog.1 |  [info] [2016-07-12T18:01:27.758Z] [on-syslog] [Syslog] [e0040e] ipxe: http://10.84.194.98:9080/centos/6/os/x86_64/images/pxeboot/initrd.img... ok
12:01:27 PM syslog.1 |   -> /lib/app.js:65
12:01:27 PM syslog.1 |  facility: 0
12:01:27 PM syslog.1 |  priority: 6
12:01:27 PM dhcp.1 |  [warning] [2016-07-12T18:01:27.788Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.
12:01:27 PM dhcp.1 |   -> /lib/message-handler.js:201
12:01:27 PM dhcp.1 |  error:
12:01:27 PM dhcp.1 |    message: Request Timed Out (on.task:methods.getBootProfile.57852a71fa76e55f11e0040e:Object).
12:01:27 PM dhcp.1 |    name:    RequestTimedOutError
12:01:27 PM dhcp.1 |    context:
12:05:45 PM http.1 |  [info] [2016-07-12T18:05:45.929Z] [on-http] [Services.Configuration] [Server] Configuration value is undefined, using default (arpCacheEnabled => true).
12:05:45 PM http.1 |   -> /node_modules/on-core/lib/services/configuration.js:73
12:05:46 PM graph.1 |  [info] [2016-07-12T18:05:46.010Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Cancelling task
12:05:46 PM graph.1 |   -> /lib/task-runner.js:193
12:05:46 PM graph.1 |  taskId: 32c693ab-8ff1-469f-a6cc-3cceccfe7e29
12:05:46 PM graph.1 |  [info] [2016-07-12T18:05:46.012Z] [on-taskgraph] [Job.Os.Install] [Server] Stopping job.
12:05:46 PM graph.1 |   -> /node_modules/on-tasks/lib/jobs/base-job.js:134
12:05:46 PM graph.1 |  taskId: 32c693ab-8ff1-469f-a6cc-3cceccfe7e29
12:05:46 PM graph.1 |  name:   InstallOsJob
12:05:46 PM graph.1 |  error:
12:05:46 PM graph.1 |    name:    TaskCancellationError
12:05:46 PM graph.1 |    context:
12:05:46 PM graph.1 |  [error] [2016-07-12T18:05:46.016Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task cancellation error
12:05:46 PM graph.1 |   -> /lib/task-runner.js:311
12:05:46 PM graph.1 |  taskRunnerId: 5c1cca97-e7a4-48f8-b710-d24500c9cdbf
12:05:46 PM graph.1 |  error:
12:05:46 PM graph.1 |  stack:
12:05:46 PM graph.1 |    """
12:05:46 PM graph.1 |      TypeError: Cannot read property 'subscribe' of undefined
12:05:46 PM graph.1 |          at MergeAllObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:3819:36)
12:05:46 PM graph.1 |          at MergeAllObserver.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at AutoDetachObserverPrototype.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
12:05:46 PM graph.1 |          at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2101:14)
12:05:46 PM graph.1 |          at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at AutoDetachObserverPrototype.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
12:05:46 PM graph.1 |          at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:4587:14)
12:05:46 PM graph.1 |          at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at AutoDetachObserverPrototype.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
12:05:46 PM graph.1 |          at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5669:29)
12:05:46 PM graph.1 |          at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at AutoDetachObserverPrototype.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
12:05:46 PM graph.1 |          at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5283:14)
12:05:46 PM graph.1 |          at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at InnerObserver.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at AutoDetachObserverPrototype.next (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5793:51)
12:05:46 PM graph.1 |          at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1721:31)
12:05:46 PM graph.1 |          at scheduleItem (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:3075:16)
12:05:46 PM graph.1 |          at JustSink.run (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:3083:9)
12:05:46 PM graph.1 |          at JustObservable.subscribeCore (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:3064:19)
12:05:46 PM graph.1 |          at JustObservable.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at setDisposable (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2038:46)
12:05:46 PM graph.1 |          at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2053:9)
12:05:46 PM graph.1 |          at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:1990:19)
12:05:46 PM graph.1 |          at MapObservable.subscribeCore (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:5268:26)
12:05:46 PM graph.1 |          at MapObservable.tryCatcher (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:63:31)
12:05:46 PM graph.1 |          at setDisposable (/root/src/on-taskgraph/node_modules/on-core/node_modules/rx/dist/rx.js:2038:46)
12:05:46 PM graph.1 |    """
12:05:46 PM graph.1 |  [error] [2016-07-12T18:05:46.036Z] [on-taskgraph] [Task.Task] [Server] Task failed
12:05:46 PM graph.1 |   -> /node_modules/on-tasks/lib/task.js:356
12:05:46 PM graph.1 |  error:          TaskCancellationError
12:05:46 PM graph.1 |  taskId:         32c693ab-8ff1-469f-a6cc-3cceccfe7e29
12:05:46 PM graph.1 |  graphId:        d52e4199-0a5f-4d36-9df8-47d7e3677bdd
12:05:46 PM graph.1 |  injectableName: Task.Os.Install.CentOS
12:05:46 PM graph.1 |  node:           57852af85f9cb453118666de
12:05:46 PM graph.1 |  [info] [2016-07-12T18:05:46.056Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
12:05:46 PM graph.1 |   -> /lib/task-runner.js:296
12:05:46 PM graph.1 |  instanceId:   32c693ab-8ff1-469f-a6cc-3cceccfe7e29
12:05:46 PM graph.1 |  state:        cancelled
12:05:46 PM graph.1 |  taskRunnerId: 5c1cca97-e7a4-48f8-b710-d24500c9cdbf
12:57:53 PM graph.1 |  [info] [2016-07-12T18:57:53.945Z] [on-taskgraph] [Job.Os.Install] [Server] Stopping job.
12:57:53 PM graph.1 |   -> /node_modules/on-tasks/lib/jobs/base-job.js:134
12:57:53 PM graph.1 |  taskId: eaf0a826-2d95-42ad-a1b1-9739ecc6e8de
12:57:53 PM graph.1 |  name:   InstallOsJob
12:57:53 PM graph.1 |  error:
12:57:53 PM graph.1 |    message: Task did not complete within 3600000ms
12:57:53 PM graph.1 |    name:    TaskTimeoutError
12:57:53 PM graph.1 |    context:
12:57:53 PM graph.1 |  [error] [2016-07-12T18:57:53.961Z] [on-taskgraph] [Task.Task] [Server] Task failed
12:57:53 PM graph.1 |   -> /node_modules/on-tasks/lib/task.js:356
12:57:53 PM graph.1 |  error:          TaskTimeoutError: Task did not complete within 3600000ms
12:57:53 PM graph.1 |  taskId:         eaf0a826-2d95-42ad-a1b1-9739ecc6e8de
12:57:53 PM graph.1 |  graphId:        6799a879-8cb1-4a61-a0da-857f48eaca12
12:57:53 PM graph.1 |  injectableName: Task.Os.Install.CentOS
12:57:53 PM graph.1 |  node:           57852a71fa76e55f11e0040e
12:57:53 PM graph.1 |  [info] [2016-07-12T18:57:53.981Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
12:57:53 PM graph.1 |   -> /lib/task-runner.js:296
12:57:53 PM graph.1 |  instanceId:   eaf0a826-2d95-42ad-a1b1-9739ecc6e8de
12:57:53 PM graph.1 |  state:        timeout
12:57:53 PM graph.1 |  taskRunnerId: 5c1cca97-e7a4-48f8-b710-d24500c9cdbf
```

**Comment by heckj** [comment]
@VulpesArtificem could you take a look - known issue that we've seen before, or a recent new critter from refactoring perhaps?

**Comment by pscharla** [comment]
Ticket in Monorail backlog now for this:
https://www.pivotaltracker.com/n/projects/1492888/stories/127812009

**Comment by pscharla** [comment]
This was closed out back in August with this PR:
https://github.com/RackHD/on-tasks/pull/261
