### ISSUE TITLE
Task.Snmp.Collect.Discovery in Graph.Switch.Discovery fails with "maxBuffer exceeded"

### ISSUE THREAD

**Issue by johren** [RackHD/RackHD#336]
We hit an issue on a particular switch where Task.Snmp.Collect.Discovery in Graph.Switch.Discovery fails with "maxBuffer exceeded".  It appears that the snmpbulkwalk is returning data that exceeds the 3MB buffer size.
```
error:
  stack:
    - Error: stdout maxBuffer exceeded.
    -     at Socket.<anonymous> (child_process.js:678:13)
    -     at Socket.EventEmitter.emit (events.js:95:17)
    -     at Socket.<anonymous> (_stream_readable.js:746:14)
    -     at Socket.EventEmitter.emit (events.js:92:17)
    -     at emitReadable_ (_stream_readable.js:408:10)
    -     at emitReadable (_stream_readable.js:404:5)
    -     at readableAddChunk (_stream_readable.js:165:9)
    -     at Socket.Readable.push (_stream_readable.js:127:10)
    -     at Pipe.onread (net.js:526:21)
  message:       stdout maxBuffer exceeded.
```
[upstart.tar.gz](https://github.com/RackHD/RackHD/files/382570/upstart.tar.gz)

It looks like it is truncating after about 94% of the output.

Attaching the full snmpbulkwalk output ([snmpbulkwalk.txt](https://github.com/RackHD/RackHD/files/382575/snmpbulkwalk.txt)
) and the logs from when this error was encountered.

**Comment by johren** [comment]
We will try to work around again by bumping the maxBuffer size, but we need a more robust solution since we will not be able to know how large the snmpbulkwalk data could get to be.

**Comment by amymullins** [comment]
Tracking stories: https://www.pivotaltracker.com/story/show/127270467

**Comment by keedya** [comment]
@johren , did u have a chance to retry to a bigger maxBuffer?

**Comment by manfrednde** [comment]
Submitted the PR: https://github.com/RackHD/on-tasks/pull/294 to increase the max buffer to 6MB as a tempory solution.

**Comment by johren** [comment]
@keedya We no longer have access to the switch that originally hit this issue.  It was on another BU's stack that is not available at this point.  They are testing across various stacks.

We did a semi-reproduction of the issue by decreasing the maxBuffer size and verifying that it hit the same error.  So we temporarily bumped up the maxBuffer size and we just hope we bumped it up far enough for now.

**Comment by yyscamper** [comment]
@keedya , @manfrednde : I think we can turn to use `child_process.spawn` rather than `child_process.exe`, the `spawn` can accept huge data output: http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

**Comment by keedya** [comment]
@yyscamper I am trying to understand the root cause of this problem. I wanted to know the MIB cmd causing this issue and if we need all this data? can we be more selective with the snmp commands and data we collect?

**Comment by johren** [comment]
@keedya:  The SNMP command causing the issue is:
/usr/bin/snmpbulkwalk -Oq -v2c -t120 -c public <ip-address> 1
