### ISSUE TITLE
SKU processing errors with traceback when no SKUs are defined in the system

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#343]
Reproduction:

git clone https://github.com/rackhd/rackhd/
cd rackhd/example
vagrant up dev && vagrant ssh dev -c "sudo nf start"
vagrant up quanta_d51

* wait for discovery process to complete
* review error in workflows output to find the error

In my case, I'd forgotten to load any SKU definitions. I expected the generate-sku task to fail, but not to error:

![screen shot 2016-07-27 at 1 23 19 pm](https://cloud.githubusercontent.com/assets/43388/17191099/518e93bc-53fd-11e6-80a4-6629de62273a.png)

Tracking down the relevant error, here's the JSON stanza from the /api/2.0/workflows output:

```
            "7e6c6646-7c71-442f-84da-ba6ce9f41b3f": {
                "error": "TypeError: Cannot read property 'catch' of undefined\n    at /home/vagrant/src/on-taskgraph/node_modules/on-tasks/lib/jobs/generate-sku.js:129:25\n    at tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)\n    at Async._drainQueue (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)",
                "friendlyName": "Generate SKU",
                "ignoreFailure": false,
                "implementsTask": "Task.Base.Catalog.GenerateSku",
                "injectableName": "Task.Catalog.GenerateSku",
                "instanceId": "7e6c6646-7c71-442f-84da-ba6ce9f41b3f",
                "label": "generate-sku",
                "name": "Task.Catalog.GenerateSku",
                "options": {
                    "_taskTimeout": 86400000,
                    "nodeId": "5799151faa0559c007dab5e3"
                },
                "properties": {},
                "runJob": "Job.Catalog.GenerateSku",
                "state": "failed",
                "taskEndTime": "2016-07-27T20:15:04.539Z",
                "taskStartTime": "2016-07-27T20:15:04.356Z",
                "terminalOnStates": [
                    "timeout",
                    "cancelled",
                    "failed"
                ],
                "waitingOn": {
                    "9beb632c-ca17-4129-bd74-271b9a30ccc6": "succeeded"
                }
            },
```

And the relevant stack trace to make it easier to read:

```
TypeError: Cannot read property 'catch' of undefined
    at /home/vagrant/src/on-taskgraph/node_modules/on-tasks/lib/jobs/generate-sku.js:129:25
    at tryCatcher (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/src/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The process *should* fail, but there shouldn't be en error reported

**Comment by zyoung51** [comment]
Fixed by: https://github.com/RackHD/on-core/pull/185.  The vagrant box does not have that fix in it.
Can you update the vagrant box to that version?

**Comment by heckj** [comment]
DOH! Thanks @zyoung51 - I thought I'd update the local code before running that sequence to verify latest before opening the bug. Clearly I didn't - will update the vagrant image.
