### ISSUE TITLE
npm install failure under node6

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#377]
@stuart-stanley reported earlier today errors while running an `npm install` using Node6.

Error happens out of the testing mechanisms:

```> on-http@0.0.0 test /Users/heckj/src/on-http
> mocha $(find spec -name '*-spec.js') -R spec --require spec/helper.js

Failed to load configuration file: /opt/monorail/config.json
Failed to load configuration file: /opt/monorail/config.json
/Users/heckj/src/on-http/node_modules/traceur/bin/traceur-runtime.js:201
      var props = $getOwnPropertyNames(source);
                  ^

TypeError: Cannot convert undefined or null to object
    at Function.assign (/Users/heckj/src/on-http/node_modules/traceur/bin/traceur-runtime.js:201:19)
    at constants.js:7:8
    at NativeModule.compile (bootstrap_node.js:455:7)
    at Function.NativeModule.require (bootstrap_node.js:396:18)
    at Function.Module._load (module.js:397:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/graceful-fs/polyfills.js:2:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/graceful-fs/graceful-fs.js:2:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/fstream/lib/reader.js:3:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/fstream/fstream.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/tar/lib/entry.js:14:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/tar/lib/entry-writer.js:5:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/tar/lib/pack.js:6:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/tar/tar.js:171:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heckj/src/on-http/lib/api/1.1/northbound/skus.js:9:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/heckj/src/on-http/node_modules/on-core/lib/di.js:529:24
    at arrayMap (/Users/heckj/src/on-http/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/heckj/src/on-http/node_modules/lodash/index.js:6710:14)
    at Object.requireGlob (/Users/heckj/src/on-http/node_modules/on-core/lib/di.js:528:14)
    at Object.onHttpContextFactory (/Users/heckj/src/on-http/index.js:41:20)
    at Object.<anonymous> (/Users/heckj/src/on-http/spec/helper.js:11:30)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/heckj/src/on-http/node_modules/mocha/bin/_mocha:311:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/heckj/src/on-http/node_modules/mocha/bin/_mocha:310:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
npm ERR! Test failed.  See above for more details.
```

traceur is from our dependency injection library
```
├─┬ di@2.0.0-pre-14 (git+https://github.com/RackHD/di.js.git#5d3f6a90e970d04cd1a
dacf40de25cbeb2a8e418)
│ ├── es6-shim@0.11.1
│ └─┬ traceur@0.0.33
```

Where we've been using a precompiled/pre-transpiled version from our node 0.10 days. Since we're now at Node4+ and can leverage ES6, we can likely use the upstream di.js (https://github.com/angular/di.js.git) directly.

@benbp indicated that our local branch also has a bit of hack (in on-http, etc) to make di a global, but if we convert to direct usage in these projects,`$provides` and `$injects` syntax instead of our global hack mechanism, we can likely use di.js directly from upstream

**Comment by yyscamper** [comment]
I just tried run `npm install` for on-http using node 6.2.2, but I didn't reproduce this issue. @stuart-stanley : Whether I miss some step?

**Comment by stuart-stanley** [comment]
@yyscamper the install works fine. It fails when you try to start the service... In my case it was trying to do the "node index.js", while I think Joe hit it trying to run the unit tests...

**Comment by heckj** [comment]
My failure was when I invoked `npm test` - and this was testing with Node v6.3.1 originally

**Comment by anhou** [comment]
Actually, travisci node 6 test always failed. https://travis-ci.org/RackHD/on-http/jobs/151541150

**Comment by stuart-stanley** [comment]
@anhou the test failure is interesting, but the import piece here is that _you can't start on-http at all using node6_. At all. Which makes it very difficult to use, if you are on a system that you can ONLY get node6 for ;).  (or at least without doing ugly hacks to get node5 into place instead!)

**Comment by pscharla** [comment]
@stuart-stanley @heckj : Just parsing through the issues list. Is this one still an active issue?  It seems dormant for nearly 3 months.

**Comment by stuart-stanley** [comment]
@pscharla : just checked, and this still fails on todays master in the same way. My understanding from what @heckj wrote above is that this will require someone with node/npm-fu to untangle. I'm getting there, but... ;)

**Comment by jeamland** [comment]
I just hit it trying to test a simple patch. =/ macOS/Homebrew node 7.0.0.
