### ISSUE TITLE
Discovered intermittent failures with on-core unit tests

### ISSUE THREAD

**Issue by DavidjohnBlodgett** [RackHD/RackHD#385]
@RackHD/corecommitters 

I have discovered that, if you switch to master of on-core and just keep running unit tests…
```while npm test; do :; done```

you will eventually hit a failure kinda like this:

```
1139 passing (22s)
  3 pending
  2 failing

  1) Model multiple records should find recently updated records with findSinceLastUpdate():
     AssertionError: expected [ Array(2) ] to have a length of 1 but got 2
      at originalMethod (node_modules/chai-as-promised/lib/chai-as-promised.js:276:69)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:310:26
      at tryCatcher (node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
      at Promise._settlePromises (node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
      at Async._drainQueue (node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)

  2) Model multiple records should find recently updated records with findSinceLastUpdate() with a query:
     AssertionError: expected [ Array(2) ] to have a length of 1 but got 2
      at originalMethod (node_modules/chai-as-promised/lib/chai-as-promised.js:276:69)
      at node_modules/chai-as-promised/lib/chai-as-promised.js:310:26
      at tryCatcher (node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
      at Promise._settlePromises (node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
      at Async._drainQueue (node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)



npm ERR! Test failed.  See above for more details.
```

and this:

```
1149 passing (21s)
  3 pending
  1 failing

  1) Lookup Service Node ID Cache should resolve pending cache checks once a value is assigned:
     Uncaught AssertionError: expected false to be truthy
```

I have rebased to current tip of master and verified the issue is still there.

**Comment by yyscamper** [comment]
I also reproduced this issue after 7 rounds to run "npm test"

**Comment by yyscamper** [comment]
add @rolandpoulter since I guess this due to the previous lookup cache design.

**Comment by rolandpoulter** [comment]
@yyscamper I dont know, what about the design is wrong?

**Comment by rolandpoulter** [comment]
Chances are this is not an issue with design and most likely a problem with the failing tests. Since the failing tests have nothing to do with lookups cache.
https://github.com/RackHD/on-core/commit/03009981659158207e52eee8149b14b1d81332ea

**Comment by rolandpoulter** [comment]
Guessing the problem with the lookups test has to do with the `setTimeout`. I was probably lazy with the test.
https://github.com/RackHD/on-core/blob/7d95f5ee3ebb8c0158f10e2d11392fa30572db48/spec/lib/services/lookup-spec.js#L107

**Comment by yyscamper** [comment]
@rolandpoulter : sorry for my rash suspicious. I have got the root cause and fix in this PR: https://github.com/RackHD/on-core/pull/205

**Comment by rolandpoulter** [comment]
Thanks @yyscamper 😄
