### ISSUE TITLE
[API 2.0] Improve the error message of invalid payload format

### ISSUE THREAD

**Issue by yyscamper** [RackHD/RackHD#389]
## Description

I purposely designed an invalid payload file with its content as following:
```
aaa
bbb
```

Then I use this payload for CentOS installation workflow, the request failed as expected, but the error message is a little and doesn't provide much useful information for user.

```
$ http POST :8080/api/2.0/nodes/57ad3694edc56b041c69a6e5/workflows?name=Graph.InstallCentOS < ~/tmp/a.txt
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 884
Content-Type: text/html; charset=utf-8
Date: Mon, 22 Aug 2016 07:04:05 GMT
X-Content-Type-Options: nosniff
X-Powered-By: Express

SyntaxError: Unexpected token a<br> &nbsp; &nbsp;at parse (/home/yuanf/src/on-http/node_modules/body-parser/lib/types/json.js:83:15)<br> &nbsp; &nbsp;at /home/yuanf/src/on-http/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/home/yuanf/src/on-http/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/home/yuanf/src/on-http/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/yuanf/src/on-http/node_modules/body-parser/node_modules/raw-body/index.js:307:7)<br> &nbsp; &nbsp;at emitNone (events.js:67:13)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:921:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickDomainCallback (node.js:397:17)

```

## Expected
1 - Wrap the error data in a JSON object, this is the common patter for other kinds of errors. 
2 - Improve the error message content and let it be more clear, in my case, I hope the error message can tell me that there is something wrong with the input payload.
3 - Don't use un-decoded characters in error message, such as \<br\> and \&nbsp;

**Comment by yyscamper** [comment]
@brianparry @keedya @srinia6

**Comment by brianparry** [comment]
@yyscamper The reason this is happening is that the error is produced by express body-parser middleware prior to the request reaching swagger middleware.  Swagger has its own parser, but the express body parser is still needed for the 1.1 API.  When that is deprecated, we should be able to remove the body-parser and contain these errors within the Swagger pipe.

**Comment by yyscamper** [comment]
@brianparry : OK, let's defer this issue after 1.1 is deprecated.
