### ISSUE TITLE
Unable to boot to local drive during active workflow.

### ISSUE THREAD

**Issue by ytjohn** [RackHD/RackHD#390]
## Background:

Fresh install in a vagrant Ubuntu 14.04 server (rachd01) attempting to pxe boot and install ubuntu onto vagrant vm pxe01. This worked with versions we had from April. We are attempting to recreate this with August versions of RackHD.

The node is booted, discovered, matches a sku, and proceeds through the workflow, getting Ubuntu installed. Once Ubuntu installs, our next task is a Noop task intended to sleep long enough for pxe01 to boot from the local hard disk. In prior versions, this worked  because on-dhcp-proxy would have no ipxe profile to send, so pxe boot would time out and default to local hard drive. In our new version,
on-dhcp-proxy sends monorail and attempts to chainload the next profile, which fails.

## versions

```
on-dhcp-proxy		1.1-1master-20160802191250Z1	RackHD Imaging workflow DHCP-Proxy engine
on-http      		1.1-1master-20160809130557Z1	RackHD HTTP engine service
on-syslog    		1.1-1master-20160802205506Z1	RackHD Syslog service component
on-taskgraph 		1.1-1master-20160803150017Z1	RackHD Imaging workflow taskgraph engine
on-tftp      		1.1-1master-20160802205406Z1	RackHD Imaging workflow tftp engine
```

## details

Our unadaltered workflow is [here](https://gist.github.com/ytjohn/16000392560ed65d3dc5409b54f0c566#file-002-workflow-regular-json), but the important portion is below. The failed pxe boot takes
place during delay-ansible-start.

[Here is the combined log from running this](https://gist.github.com/ytjohn/16000392560ed65d3dc5409b54f0c566#file-fulllog-2-log)

```
    "install-ubuntu": {
      "profile": "install-trusty.ipxe",
      "version": "trusty",
      "username": "renasar",
      "password": "renasar",
      "uid": "1010",
      "hostname": "{{ context.rubicon.config_values.hostname }}",
      "domain": "{{ context.rubicon.config_values.domain }}"
    },
    "delay-ansible-start": {
      "delay": 300000
    },
    "ansible-post-install": {
      "playbook": "/opt/rackhd/ansible/site.yml",
      "vars": {
        "metallica_role": "vagrant-trusty"
      }
    }
```

Our workaround was to attempt adding a Disk Boot task between install-ubuntu and delay-ansible-start. [link](https://gist.github.com/ytjohn/16000392560ed65d3dc5409b54f0c566#file-003-workflow-graph-withboot-json).  [Combined log](https://gist.github.com/ytjohn/16000392560ed65d3dc5409b54f0c566#file-fulllog-3-log)

(note: diskboot.ipxe will not work in a vagrant environment, we have an error.ipxe that issues a sanboot command that works)
error.ipxe (`sanboot --no-describe --drive 0x80`)

New graph:

```
options: {
    "boot-to-disk": {
        "profile": "error.ipxe"
    }
}

...

{
      "label": "install-ubuntu",
      "taskName": "Task.Os.Install.Ubuntu",
      "waitOn": {
        "shell-reboot": "succeeded"
      }
    },
    {
      "label": "boot-to-disk",
      "taskName": "Task.BootProfile",
      "waitOn": {
        "install-ubuntu": "succeeded"
      }
    },
    {
      "label": "delay-ansible-start",
      "taskName": "Task.noop",
      "waitOn": {
        "boot-to-disk": "succeeded"
      }
    },
    {
      "label": "ansible-post-install",
      "taskName": "Task.Base.Ansible.PostInstall",
      "waitOn": {
        "delay-ansible-start": "finished"
      }
    }
```

With this graph, it proceeds in the same way, but we get the 503 during the boot-to-disk task. We get the same
results no matter which profile we define (bootdisk.ipxe or error.ipxe).

The node does not receive our ipxe file, it fails to boot, and then taskgraph marks the boot-to-disk task as succeeded. Subsequent
tasks will fail because the node is not up.  However, if are reboot the vm, watch console and hit "ESC" during ipxe boot, it will cancel ipxe and boot 
into the hard drive, allowing the remaining tasks to succeed.

```
==> /var/log/rackhd/on-taskgraph.log <==
[debug] [2016-08-23T17:09:56.582Z] [on-taskgraph] [Job.BootProfile] [7c72fe] Running job.
 -> /node_modules/on-tasks/lib/jobs/base-job.js:112
module:  Job.BootProfile
name:    BootProfileJob
options: 
  profile:      error.ipxe
  _taskTimeout: 86400000
taskId:  2515fa69-4293-4646-9067-03907323a8df
target:  57bc81b9cb0345ac7f7c72fe

==> /var/log/rackhd/on-dhcp-proxy.log <==
[debug] [2016-08-23T17:10:04.179Z] [on-dhcp-proxy] [DHCP.parser] [7c72fe] Unhandled DHCP options (97:17,94:3)
 -> /lib/parser.js:331
macaddress: 08:00:27:bc:f8:88
[warning] [2016-08-23T17:10:05.211Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.
 -> /lib/message-handler.js:201
error: 
  message: Request Timed Out (on.task:methods.getBootProfile.57bc81b9cb0345ac7f7c72fe:Object).
  name:    RequestTimedOutError
  context: 

==> /var/log/rackhd/on-http.log <==
[debug] [2016-08-23T17:10:06.366Z] [on-http] [Http.Server] [7c72fe] http: GET 200 17.542 - /api/current/profiles
 -> /lib/services/http-service.js:333
ipAddress: 192.168.37.201

==> /var/log/rackhd/on-syslog.log <==
[info] [2016-08-23T17:10:07.414Z] [on-syslog] [Syslog] [7c72fe] ipxe: Configuring (net0 08:00:27:bc:f8:88).... ok
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-23T17:10:07.418Z] [on-syslog] [Syslog] [7c72fe] ipxe: net0: 192.168.37.201/255.255.255.0
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-23T17:10:07.419Z] [on-syslog] [Syslog] [7c72fe] ipxe: MonoRail Boilerplate iPXE Completed.
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-23T17:10:07.423Z] [on-syslog] [Syslog] [7c72fe] ipxe:
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-23T17:10:07.424Z] [on-syslog] [Syslog] [7c72fe] ipxe: Chainloading next profile
 -> /lib/app.js:65
facility: 0
priority: 6


==> /var/log/rackhd/on-taskgraph.log <==
[info] [2016-08-23T17:10:07.466Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
 -> /lib/task-runner.js:296
instanceId:   2515fa69-4293-4646-9067-03907323a8df
state:        succeeded
taskRunnerId: f1e7440f-8c4e-4e4d-86b8-c6d06ff467f8


```

**Comment by ytjohn** [comment]
@jlmcknight @anhou @benbp

**Comment by anhou** [comment]
@ytjohn Could you have a try with "diskboot.ipxe"?  I validate this profile task, it work, the screenshot is as below. It has 'Diskboot' printed in console
![image](https://cloud.githubusercontent.com/assets/14013330/17923386/883a84be-6a16-11e6-8783-691d68bff177.png)

**Comment by ytjohn** [comment]
Can you share your graph? I simplified things on my end and made diskboot the last step in the graph. 

![image](https://cloud.githubusercontent.com/assets/163156/17932559/8f2ca9ce-69de-11e6-9855-a68a815cedce.png)


```
    "boot-to-disk": {
        "profile": "diskboot.ipxe"
    }
    ...
    {
      "label": "install-ubuntu",
      "taskName": "Task.Os.Install.Ubuntu",
      "waitOn": {
        "shell-reboot": "succeeded"
      }
    },
    {
      "label": "boot-to-disk",
      "taskName": "Task.BootProfile",
      "waitOn": {
        "install-ubuntu": "succeeded"
      }
    }
```

Log Output
    
```
==> /var/log/rackhd/on-taskgraph.log <==
[debug] [2016-08-24T13:21:44.633Z] [on-taskgraph] [TaskGraph.TaskScheduler] [Server] Task scheduled
 -> /lib/task-scheduler.js:471
domain:      default
graphId:     6386b010-87b3-4066-b437-e8f1190f7de6
taskId:      41207f41-fb89-4423-a155-d0e8bc0719a7
schedulerId: 58b4af02-0230-4c20-89f4-d5f897f45fc6
[info] [2016-08-24T13:21:44.650Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Running task 
 -> /lib/task-runner.js:340
taskRunnerId: 4712a070-1a3d-438e-b734-fdfcf70b17cf
taskId:       41207f41-fb89-4423-a155-d0e8bc0719a7
taskName:     Task.BootProfile
[info] [2016-08-24T13:21:44.669Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:361
taskId: 41207f41-fb89-4423-a155-d0e8bc0719a7
name:   Boot Profile
job:    Job.BootProfile

==> /var/log/rackhd/on-taskgraph.log <==
module:  Job.BootProfile
name:    BootProfileJob
options: 
  profile:      diskboot.ipxe
  _taskTimeout: 86400000
taskId:  41207f41-fb89-4423-a155-d0e8bc0719a7
target:  57bd9dac446ad5ab6bc38f28

==> /var/log/rackhd/on-http.log <==
[debug] [2016-08-24T13:21:54.613Z] [on-http] [Http.Server] [c38f28] http: GET 200 19.550 - /api/current/profiles
 -> /lib/services/http-service.js:333
ipAddress: 192.168.37.201

==> /var/log/rackhd/on-dhcp-proxy.log <==
[debug] [2016-08-24T13:21:54.624Z] [on-dhcp-proxy] [DHCP.parser] [c38f28] Unhandled DHCP options (94:3,175:51,97:17)
 -> /lib/parser.js:331
macaddress: 08:00:27:bc:f8:88
[warning] [2016-08-24T13:21:54.945Z] [on-dhcp-proxy] [DHCP.messageHandler] [Server] Could not get TFTP bootfile name from active task. Sending default bootfile.


==> /var/log/rackhd/on-syslog.log <==
[info] [2016-08-24T13:21:55.666Z] [on-syslog] [Syslog] [c38f28] ipxe: Configuring (net0 08:00:27:bc:f8:88).... ok
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-24T13:21:55.667Z] [on-syslog] [Syslog] [c38f28] ipxe: net0: 192.168.37.201/255.255.255.0
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-24T13:21:55.680Z] [on-syslog] [Syslog] [c38f28] ipxe: MonoRail Boilerplate iPXE Completed.
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-24T13:21:55.684Z] [on-syslog] [Syslog] [c38f28] ipxe:
 -> /lib/app.js:65
facility: 0
priority: 6
[info] [2016-08-24T13:21:55.688Z] [on-syslog] [Syslog] [c38f28] ipxe: Chainloading next profile
 -> /lib/app.js:65
facility: 0
priority: 6

==> /var/log/rackhd/on-taskgraph.log <==
[info] [2016-08-24T13:21:55.730Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
 -> /lib/task-runner.js:296

==> /var/log/rackhd/on-http.log <==
[error] [2016-08-24T13:21:56.765Z] [on-http] [common-api-presenter] [Server] Request Timed Out (on.task:methods.activeTaskExists.57bd9dac446ad5ab6bc38f28:Object).
 -> /lib/services/common-api-presenter.js:110
error: 
  message: Request Timed Out (on.task:methods.activeTaskExists.57bd9dac446ad5ab6bc38f28:Object).
  name:    RequestTimedOutError
  context: 

path:  /profiles
[debug] [2016-08-24T13:21:56.772Z] [on-http] [Http.Server] [c38f28] http: GET 500 1081.474 - /api/current/profiles?macs=08%3A00%3A27%3Abc%3Af8%3A88
 -> /lib/services/http-service.js:333
ipAddress: 192.168.37.201

==> /var/log/rackhd/on-syslog.log <==
[info] [2016-08-24T13:21:56.771Z] [on-syslog] [Syslog] [c38f28] ipxe: Failed to download profile, retrying in 3 seconds
 -> /lib/app.js:65
facility: 0
priority: 6

==> /var/log/rackhd/on-syslog.log <==
[info] [2016-08-24T13:21:59.745Z] [on-syslog] [Syslog] [c38f28] ipxe: Chainloading next profile
 -> /lib/app.js:65
facility: 0
priority: 6

==> /var/log/rackhd/on-http.log <==
Using monkey-patched Error.prototype.toJSON method, which will be deprecated soon.
[error] [2016-08-24T13:21:59.812Z] [on-http] [common-api-presenter] [Server] Error: Unable to locate active workflow or there are no bootSettings
 -> /lib/services/common-api-presenter.js:110
error: 
  stack: 
    - Error: Error: Unable to locate active workflow or there are no bootSettings
    -     at ProfileApiService._handleProfileRenderError (/var/renasar/on-http/lib/services/profiles-api-service.js:249:19)
    -     at /var/renasar/on-http/lib/services/profiles-api-service.js:318:33
    -     at tryCatcher (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    -     at Promise._settlePromiseFromHandler (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    -     at Promise._settlePromiseAt (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    -     at Promise._settlePromises (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    -     at Async._drainQueue (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    -     at Async._drainQueues (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    -     at Immediate.Async.drainQueues [as _onImmediate] (/var/renasar/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    -     at processImmediate [as _immediateCallback] (timers.js:383:17)
  message: Error: Unable to locate active workflow or there are no bootSettings
  status:  400
path:  /profiles
Using monkey-patched Error.prototype.toJSON method, which will be deprecated soon.

```

**Comment by anhou** [comment]
@ytjohn  I create a simple graph  "on-taskgraph/lib/graphs/boot-disk-graph.js" and restart on-taskgraph to validate it. the contents are below

```
// Copyright 2015, EMC, Inc.

'use strict';

module.exports = {
    friendlyName: 'Boot Disk',
    injectableName: 'Graph.BootDisk',
    options: {
        'boot-profile': {
            "profile": "diskboot.ipxe"
        }
    },
    tasks: [
        {
            label: 'boot-profile',
            taskName: 'Task.BootProfile'
        }
    ]
};

```

**Comment by anhou** [comment]
@ytjohn I think I've found what's the issue. I see errors 'Error: Error: Unable to locate active workflow or there are no bootSettings' in your post logs. in the latest on-http master branch codes. this is not treated as an error, it's  https://github.com/RackHD/on-http/blob/master/lib/services/profiles-api-service.js#L329 now. So just please update the latest on-http codes and have a try, any problems, let me know

**Comment by ytjohn** [comment]
@anhou  upgrading on-http does make the profile work.  It sent the diskboot.ipxe.  I'll have to make a diskboot-sanboot.ipxe because vagrant (and some hardware) does not automatically move on.

![image](https://cloud.githubusercontent.com/assets/163156/17940477/5e301328-69fd-11e6-8a8b-e631cb39818c.png)

**Comment by benbp** [comment]
@ytjohn yeah I've had the same trouble with virtualbox, but if I recall correctly the sanboot 0x80 thing does work. Let me know if you have success with that (and if so, please put up a PR).

**Comment by ytjohn** [comment]
I have successfully worked through this using the newer on-http version and sanboot.  My issue is resolved. It might be worth having a discussion if you want the regular diskboot.ipxe to include the sanboot command or not.  

diskboot-sanboot.ipxe
```
echo Diskboot, forced
sanboot --no-describe --drive 0x80
```

**Comment by heckj** [comment]
@ytjohn should we have a specific `diskboot-sanboot.ipxe` like this in our codebase for this solution? What caveats would you put around others using it?

**Comment by ytjohn** [comment]
@heckj  I think it would be worth having included, but not as a default. I think for most hardware, just simply using the regular diskboot.ipxe would be fine. But some hardware (and virtual machines) will get stuck in the failed pxe boot unless you send the sanboot command.

The caveat would be that it could negate a bios boot order.  `sanboot --no-describe --drive 0x80` explicitly boots from the first disk.  http://ipxe.org/cmd/sanboot`.  I would name it something more descriptive like bootdisk-firstdisk.ipxe so people know what they're getting.  

http://ipxe.org/cmd/sanboot
https://github.com/puppetlabs/Razor/issues/409

**Comment by anhou** [comment]
@ytjohn @benbp @heckj  for original diskboot.ipxe, it only has `echo Diskboot` , actually, it just skip ipxe boot to next boot order.  maybe it should be name `skip-ipxe-boot.ipxe` or other more descriptive name.

**Comment by heckj** [comment]
@ytjohn thanks - made two PR's (one just updating a comment) to make these changes - this match what you're thinking?

I didn't spot any other locations where diskboot.ipxe was in use within code, but definitely want another eye on this.

**Comment by ytjohn** [comment]
@heckj somehow missed this, but yes, that matches what I was thinking.
