### ISSUE TITLE
profile load error with Node 4.2.3

### ISSUE THREAD

**Issue by heckj** [RackHD/RackHD#40]
@kacole2 was dockerizing the applications for RackHD, using Node 4.2.3 and ran into this traceback while attempting to run and start on-http:

```
W 2015-12-14T20:37:30.275Z [on-http] [Profiles] [Server] Unable to load profiles from /usr/src/on-http/data/profiles.
 -> /node_modules/on-core/lib/common/profile.js:49
error:
  stack:
    - TypeError: must start with number, buffer, array or string
    -     at fromObject (buffer.js:139:11)
    -     at new Buffer (buffer.js:58:10)
    -     at initCloneByTag (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:4026:18)
    -     at baseClone (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:1718:15)
    -     at /usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:1738:23
    -     at /usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:3106:15
    -     at baseForOwn (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:2053:14)
    -     at baseClone (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:1737:39)
    -     at Function.cloneDeep (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/lodash/index.js:8346:11)
    -     at module.exports [as create] (/usr/src/on-http/node_modules/on-core/node_modules/waterline/lib/waterline/query/dql/create.js:42:14)
    -     at /usr/src/on-http/node_modules/on-core/lib/common/profile.js:70:47
    -     at tryCatcher (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    -     at Promise._settlePromiseFromHandler (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    -     at Promise._settlePromiseAt (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    -     at Promise._settlePromises (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    -     at Async._drainQueue (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    -     at Async._drainQueues (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    -     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/on-http/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    -     at processImmediate [as _immediateCallback] (timers.js:383:17)
  message: must start with number, buffer, array or string```

**Comment by kacole2** [comment]
here is the dockerfile for anyone's purpose
```
############################################################
# Dockerfile to start the on-http service of RackHD
############################################################

# docker run -d --name on-http --net=isolated_nw /
# --restart=always -p 514:514
# -e "amqp=amqp://rackhd-rabbit" /
# -e "mongo=mongodb://rackhd-mongo/rackhd"
# -e "statsd=rackhd-statsd:8125" rackhd/on-http

# Based on Node.js
FROM node:argon
EXPOSE 80
# Update the repository sources list
RUN apt-get update

# Set Environment Variables.
ENV amqp $amqp
ENV mongo $mongo
ENV statsd $statsd

# Build from Repo
WORKDIR /usr/src
RUN git clone https://github.com/RackHD/on-http
WORKDIR /usr/src/on-http
RUN rm -rf node_modules
RUN npm install
RUN npm run apidoc

# Set default container command
ENTRYPOINT ["node"]

# Start the http service
CMD ["index.js"]
```
