### ISSUE TITLE
[Travis-CI] npm install see failure 

### ISSUE THREAD

**Issue by panpan0000** [RackHD/RackHD#461]
Travis-CI:

there will be a "gyp ERR" during "npm install --production" , when build debian package on-tftp:

https://travis-ci.org/RackHD/on-tftp/jobs/159473869

this issue can't be reproduced locally with same NodeJS version 4.6.1
-------
unfolder Line 781
find Line 1152
```
../node_modules/nan/nan_new.h:29:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/travis/build/RackHD/on-tftp/packagebuild/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.6.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.6.1/bin/node" "/home/travis/.nvm/versions/node/v4.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/RackHD/on-tftp/packagebuild/node_modules/on-core/node_modules/sails-mongo/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by yyscamper** [comment]
I see this post in nodejs repo: https://github.com/nodejs/node-gyp/issues/940
