### ISSUE TITLE
networkDevices assignment into the bootimage payload is causing the bootImage process to fail. 

### ISSUE THREAD

**Issue by miramm** [RackHD/RackHD#464]
The api output reported that the execution was a success but the output shows that it failed right at the initial step of the workflow.  

Payload used:

```
{
                "version": "6.0",
                "osName": "ESXi",
                "repo": "http://172.31.128.1:9080/esxi6.0/esxi6",
                "rootPassword": "1234567",
                "hostname": "ESXi60",
                "networkDevices": [
                                        {
                        "device": "vmnic1",
                        "ipv4":
                            {"netmask": "255.255.252.0", "ipAddr": "172.31.128.240", "gateway": "172.31.128.1"}

                    }
                ],
                "domain": "hwimo.lab.emc.com",
                "dnsServers": ["10.253.130.61"],
                "users": [
                    {"name": "onrack", "password": "Onr@ck1!", "uid": 1010}
                ]
}
```

stack: 
  """
    TypeError: Cannot read property 'tasks' of undefined
        at /var/renasar/on-taskgraph/node_modules/on-core/lib/workflow/stores/mongo.js:374:36
        at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
        at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
        at Promise._settlePromises (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
        at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate](/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback](timers.js:383:17)
  """

**Comment by yyscamper** [comment]
@miramm : Which RackHD version you were using? I tried this payload in my system, it worked well.

**Comment by miramm** [comment]
@yyscamper 
Is there a command to check the RackHD version?

**Comment by miramm** [comment]
@yyscamper 
the code was about a week old. I don't know if there's a command to determine the build versions. 

I took another snapshot today and the problem got resolved with the latest code. 

taskName:     Task.Ssh.Validation
[info] [2016-10-31T14:39:40.192Z] [on-taskgraph] [Task.Task] [Server] Running task job.
 -> /node_modules/on-tasks/lib/task.js:377
taskId: 77134156-4cd6-4875-8e1e-8684d2f34522
name:   Validate Ssh
job:    Job.Ssh.Validation
[info] [2016-10-31T14:39:55.432Z] [on-taskgraph] [TaskGraph.TaskRunner] [Server] Task finished
 -> /lib/task-runner.js:296
instanceId:   77134156-4cd6-4875-8e1e-8684d2f34522
state:        succeeded
taskRunnerId: e5bf23dd-63a6-41d1-bf3a-3dd99610abc2

**Comment by leoyjchang** [comment]
@miramm glad to know this issue was resolved with latest code. Do you mind if closing this ticket?

**Comment by miramm** [comment]
@leoyjchang Yes, it can be close. 
thanks.
